// Copyright 2017 Masaki Hara. See the COPYRIGHT
// file at the top-level directory of this distribution.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

#include "main_rb.h"
#include <stdbool.h>
#include <ruby.h>
#include "sdl_misc.h"
#include "RGSSReset.h"

#if RGSS == 3
#define SCRIPT_PATH "\"Data/Scripts.rvdata2\""
#elif RGSS == 2
#define SCRIPT_PATH "\"Data/Scripts.rvdata\""
#else
#define SCRIPT_PATH "\"Data/Scripts.rxdata\""
#endif

static VALUE rescue_any(VALUE data, VALUE e);
static VALUE main_rb2(VALUE data);
static void load_libs(void);
static void load_scripts(void);
static VALUE rescue_reset(VALUE data, VALUE e);
static VALUE load_scripts2(VALUE data);

#if RGSS == 3
static VALUE rb_rgss_main(VALUE self);
static VALUE rb_rgss_main2(VALUE data);
#endif

VALUE main_rb(VALUE data) {
#if RGSS == 3
  rb_define_global_function("rgss_main", rb_rgss_main, 0);
#endif
  return rb_rescue2(main_rb2, data, rescue_any, Qnil, rb_eException, NULL);
}

static VALUE rescue_any(VALUE data, VALUE e) {
  (void) data;
  (void) e;
  rb_eval_string(
      "  $stderr.print(\"#{$!.class}: #{$!.message}\\n\")\n"
      "  $!.backtrace.each do|frame|\n"
      "    $stderr.print(\"\\tfrom #{frame}\\n\")\n"
      "  end\n"
  );
  return Qnil;
}

static VALUE main_rb2(VALUE data) {
  (void) data;
  load_libs();
  load_scripts();
  return Qnil;
}

static void load_libs() {
  rb_eval_string(
#if RGSS < 3
      "$KCODE = \"u\"\n"
#endif
      /* TODO: this is only for developing purpose. */
      /* We want to remove it when it becomes unnecessary. */
      "def warn_unimplemented(name)\n"
      "  unimplemented_warnings = eval(\"$unimplemented_warnings ||= {}\")\n"
      "  if !unimplemented_warnings[name]\n"
      "    unimplemented_warnings[name] = true\n"
      "    $stderr.puts \"unimplemented: #{name}\"\n"
      "  end\n"
      "end\n"
      "class Font\n"
#if RGSS == 3
      "  @@default_name = \"VL Gothic\"\n"
      "  @@default_size = 24\n"
#elif RGSS == 2
      "  @@default_name = [\"UmePlus Gothic\", \"ＭＳ ゴシック\", \"Courier New\"] \n"
      "  @@default_size = 20\n"
#else
      "  @@default_name = \"ＭＳ Ｐゴシック\"\n"
      "  @@default_size = 22\n"
#endif
      "  @@default_bold = false\n"
      "  @@default_italic = false\n"
#if RGSS == 3
      "  @@default_outline = true\n"
      "  @@default_shadow = false\n"
#elif RGSS == 2
      "  @@default_shadow = true\n"
#endif
      "  @@default_color = Color.new(255, 255, 255, 255)\n"
#if RGSS == 3
      "  @@default_out_color = Color.new(0, 0, 0, 128)\n"
#endif
      "  def self.default_name\n"
      "    @@default_name\n"
      "  end\n"
      "  def self.default_name=(default_name)\n"
      "    @@default_name = default_name\n"
      "  end\n"
      "  def self.default_size\n"
      "    @@default_size\n"
      "  end\n"
      "  def self.default_size=(default_size)\n"
      "    @@default_size = default_size\n"
      "  end\n"
      "  def self.default_bold\n"
      "    @@default_bold\n"
      "  end\n"
      "  def self.default_bold=(default_bold)\n"
      "    @@default_bold = default_bold\n"
      "  end\n"
      "  def self.default_italic\n"
      "    @@default_italic\n"
      "  end\n"
      "  def self.default_italic=(default_italic)\n"
      "    @@default_italic = default_italic\n"
      "  end\n"
#if RGSS == 3
      "  def self.default_outline\n"
      "    @@default_outline\n"
      "  end\n"
      "  def self.default_outline=(default_outline)\n"
      "    @@default_outline = default_outline\n"
      "  end\n"
#endif
#if RGSS >= 2
      "  def self.default_shadow\n"
      "    @@default_shadow\n"
      "  end\n"
      "  def self.default_shadow=(default_shadow)\n"
      "    @@default_shadow = default_shadow\n"
      "  end\n"
#endif
      "  def self.default_color\n"
      "    @@default_color\n"
      "  end\n"
      "  def self.default_color=(default_color)\n"
      "    @@default_color = default_color\n"
      "  end\n"
#if RGSS == 3
      "  def self.default_out_color\n"
      "    @@default_out_color\n"
      "  end\n"
      "  def self.default_out_color=(default_out_color)\n"
      "    @@default_out_color = default_out_color\n"
      "  end\n"
#endif
      "end\n"
      "\n"
      "module RPG\n"
      "  class Map\n"
      "    attr_accessor :autoplay_bgm, :autoplay_bgs, :bgm, :bgs, :data, :encounter_list, :encounter_step, :events, :height, :width\n"
#if RGSS >= 2
      "    attr_accessor :disable_dashing, :parallax_loop_x, :parallax_loop_y, :parallax_name, :parallax_show, :parallax_sx, :parallax_sy, :scroll_type\n"
#endif
#if RGSS == 3
      "    attr_accessor :battleback1_name, :battleback2_name, :display_name, :note, :specify_battleback, :tileset_id\n"
#endif
#if RGSS == 1
      "    attr_accessor :tileset_id\n"
#endif
      "    def initialize(width, height)\n"
#if RGSS == 3
      "      @autoplay_bgm = false\n"
      "      @autoplay_bgs = false\n"
      "      @battleback1_name = \"\"\n"
      "      @battleback2_name = \"\"\n"
      "      @bgm = RPG::BGM.new\n"
      "      @bgs = RPG::BGS.new(\"\", 80)\n"
      "      @data = Table.new(width, height, 4)\n"
      "      @disable_dashing = false\n"
      "      @display_name = \"\"\n"
      "      @encounter_list = []\n"
      "      @encounter_step = 30\n"
      "      @events = {}\n"
      "      @height = height\n"
      "      @note = \"\"\n"
      "      @parallax_loop_x = false\n"
      "      @parallax_loop_y = false\n"
      "      @parallax_name = \"\"\n"
      "      @parallax_show = false\n"
      "      @parallax_sx = 0\n"
      "      @parallax_sy = 0\n"
      "      @scroll_type = 0\n"
      "      @specify_battleback = false\n"
      "      @tileset_id = 1\n"
      "      @width = width\n"
#elif RGSS == 2
      "      @autoplay_bgm = false\n"
      "      @autoplay_bgs = false\n"
      "      @bgm = RPG::BGM.new\n"
      "      @bgs = RPG::BGS.new(\"\", 80)\n"
      "      @data = Table.new(width, height, 3)\n"
      "      @disable_dashing = false\n"
      "      @encounter_list = []\n"
      "      @encounter_step = 30\n"
      "      @events = {}\n"
      "      @height = height\n"
      "      @parallax_loop_x = false\n"
      "      @parallax_loop_y = false\n"
      "      @parallax_name = \"\"\n"
      "      @parallax_show = false\n"
      "      @parallax_sx = 0\n"
      "      @parallax_sy = 0\n"
      "      @scroll_type = 0\n"
      "      @width = width\n"
#else
      "      @autoplay_bgm = false\n"
      "      @autoplay_bgs = false\n"
      "      @bgm = RPG::AudioFile.new\n"
      "      @bgs = RPG::AudioFile.new(\"\", 80)\n"
      "      @data = Table.new(width, height, 3)\n"
      "      @encounter_list = []\n"
      "      @encounter_step = 30\n"
      "      @events = {}\n"
      "      @height = height\n"
      "      @tileset_id = 1\n"
      "      @width = width\n"
#endif
      "    end\n"
#if RGSS == 3
      "    class Encounter\n"
      "      attr_accessor :region_set, :troop_id, :weight\n"
      "      def initialize\n"
      "        @region_set = []\n"
      "        @troop_id = 1\n"
      "        @weight = 10\n"
      "      end\n"
      "    end\n"
#endif
      "  end\n"
      "  class MapInfo\n"
      "    attr_accessor :expanded, :name, :order, :parent_id, :scroll_x, :scroll_y\n"
      "    def initialize\n"
      "      @expanded = false\n"
      "      @name = \"\"\n"
      "      @order = 0\n"
      "      @parent_id = 0\n"
      "      @scroll_x = 0\n"
      "      @scroll_y = 0\n"
      "    end\n"
      "  end\n"
#if RGSS == 2
      "  class Area\n"
      "    attr_accessor :encounter_list, :id, :map_id, :name, :order, :rect\n"
      "    def initialize\n"
      "      @encounter_list = []\n"
      "      @id = 0\n"
      "      @map_id = 0\n"
      "      @name = \"\"\n"
      "      @order = 0\n"
      "      @rect = Rect.new(0, 0, 0, 0)\n"
      "    end\n"
      "  end\n"
#endif
      "  class Event\n"
      "    attr_accessor :id, :name, :pages, :x, :y\n"
      "    def initialize(x, y)\n"
      "      @id = 0\n"
      "      @name = \"\"\n"
      "      @pages = [RPG::Event::Page.new]\n"
      "      @x = x\n"
      "      @y = y\n"
      "    end\n"
      "    class Page\n"
      "      attr_accessor :condition, :direction_fix, :graphic, :list, :move_frequency, :move_route, :move_speed, :move_type, :step_anime, :through, :trigger, :walk_anime\n"
#if RGSS >= 2
      "      attr_accessor :priority_type\n"
#elif RGSS == 1
      "      attr_accessor :always_on_top\n"
#endif
      "      def initialize\n"
      "        @condition = RPG::Event::Page::Condition.new\n"
      "        @direction_fix = false\n"
      "        @graphic = RPG::Event::Page::Graphic.new\n"
      "        @list = [RPG::EventCommand.new]\n"
      "        @move_frequency = 3\n"
      "        @move_route = RPG::MoveRoute.new\n"
      "        @move_speed = 3\n"
      "        @move_type = 0\n"
      "        @step_anime = false\n"
      "        @through = false\n"
      "        @trigger = 0\n"
      "        @walk_anime = true\n"
#if RGSS >= 2
      "        @priority_type = 0\n"
#elif RGSS == 1
      "        @always_on_top = false\n"
#endif
      "      end\n"
      "      class Condition\n"
      "        attr_accessor :self_switch_ch, :self_switch_valid, :switch1_id, :switch1_valid, :switch2_id, :switch2_valid, :variable_id, :variable_valid, :variable_value\n"
#if RGSS >= 2
      "        attr_accessor :actor_id, :actor_valid, :item_id, :item_valid\n"
#endif
      "        def initialize\n"
      "          @self_switch_ch = \"A\"\n"
      "          @self_switch_valid = false\n"
      "          @switch1_id = 1\n"
      "          @switch1_valid = false\n"
      "          @switch2_id = 1\n"
      "          @switch2_valid = false\n"
      "          @variable_id = 1\n"
      "          @variable_valid = false\n"
      "          @variable_value = 0\n"
#if RGSS >= 2
      "          @actor_id = 1\n"
      "          @actor_valid = false\n"
      "          @item_id = 1\n"
      "          @item_valid = false\n"
#endif
      "        end\n"
      "      end\n"
      "      class Graphic\n"
      "        attr_accessor :character_name, :direction, :pattern, :tile_id\n"
#if RGSS >= 2
      "        attr_accessor :character_index\n"
#else
      "        attr_accessor :blend_type, :character_hue, :opacity\n"
#endif
      "        def initialize\n"
      "          @character_name = \"\"\n"
      "          @direction = 2\n"
      "          @pattern = 0\n"
      "          @tile_id = 0\n"
#if RGSS >= 2
      "          @character_index = 0\n"
#else
      "          @blend_type = 0\n"
      "          @character_hue = 0\n"
      "          @opacity = 255\n"
#endif
      "        end\n"
      "      end\n"
      "    end\n"
      "  end\n"
      "  class EventCommand\n"
      "    attr_accessor :code, :indent, :parameters\n"
      "    def initialize(code = 0, indent = 0, parameters = [])\n"
      "      @code = code\n"
      "      @indent = indent\n"
      "      @parameters = parameters\n"
      "    end\n"
      "  end\n"
      "  class MoveRoute\n"
      "    attr_accessor :list, :repeat, :skippable\n"
#if RGSS >= 2
      "    attr_accessor :wait\n"
#endif
      "    def initialize\n"
      "      @list = [RPG::MoveCommand.new]\n"
      "      @repeat = true\n"
      "      @skippable = false\n"
#if RGSS >= 2
      "      @wait = false\n"
#endif
      "    end\n"
      "  end\n"
      "  class MoveCommand\n"
      "    attr_accessor :code, :parameters\n"
      "    def initialize(code = 0, parameters = [])\n"
      "      @code = code\n"
      "      @parameters = parameters\n"
      "    end\n"
      "  end\n"
#if RGSS >= 2
      "  class BaseItem\n"
      "    attr_accessor :description, :icon_index, :id, :name, :note\n"
#if RGSS == 3
      "    attr_accessor :features\n"
      "    class Feature\n"
      "      attr_accessor :code, :data_id, :value\n"
      "      def initialize(code = 0, data_id = 0, value = 0)\n"
      "        @code = code\n"
      "        @data_id = data_id\n"
      "        @value = value\n"
      "      end\n"
      "    end\n"
#endif
      "    def initialize\n"
      "      @description = \"\"\n"
      "      @icon_index = 0\n"
      "      @id = 0\n"
      "      @name = \"\"\n"
      "      @note = \"\"\n"
#if RGSS == 3
      "      @features = []\n"
#endif
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Actor < BaseItem\n"
      "    attr_accessor :character_index, :character_name, :class_id, :equips, :face_index, :face_name, :initial_level, :max_level, :nickname\n"
      "    def initialize\n"
      "      super\n"
      "      @character_index = 0\n"
      "      @character_name = \"\"\n"
      "      @class_id = 1\n"
      "      @equips = [0, 0, 0, 0, 0]\n"
      "      @face_index = 0\n"
      "      @face_name = \"\"\n"
      "      @initial_level = 1\n"
      "      @max_level = 99\n"
      "      @nickname = \"\"\n"
      "    end\n"
      "  end\n"
#else
      "  class Actor\n"
      "    attr_accessor :armor1_id, :armor2_id, :armor3_id, :armor4_id, :class_id, :exp_basis, :exp_inflation, :id, :initial_level, :name, :parameters, :weapon_id\n"
#if RGSS == 2
      "    attr_accessor :auto_battle, :character_index, :character_name, :critical_bonus, :face_index, :face_name, :fix_equipment, :pharmacology, :super_guard, :two_swords_style\n"
#else
      "    attr_accessor :armor1_fix, :armor2_fix, :armor3_fix, :armor4_fix, :battler_hue, :battler_name, :character_hue, :character_name, :final_level, :weapon_fix\n"
#endif
      "    def initialize\n"
      "      @armor1_id = 0\n"
      "      @armor2_id = 0\n"
      "      @armor3_id = 0\n"
      "      @armor4_id = 0\n"
      "      @class_id = 1\n"
      "      @id = 0\n"
      "      @initial_level = 1\n"
      "      @name = \"\"\n"
      "      @weapon_id = 0\n"
#if RGSS == 2
      "      @auto_battle = false\n"
      "      @character_index = 0\n"
      "      @character_name = \"\"\n"
      "      @critical_bonus = false\n"
      "      @exp_basis = 25\n"
      "      @exp_inflation = 35\n"
      "      @face_index = 0\n"
      "      @face_name = \"\"\n"
      "      @fix_equipment = false\n"
      "      @parameters = Table.new(6, 100)\n"
      "      (1..99).each do|level|\n"
      "        @parameters[0, level] = level * 50 + 400\n"
      "        @parameters[1, level] = level * 10 + 80\n"
      "        @parameters[2, level] = (level * 5 + 60) / 4\n"
      "        @parameters[3, level] = (level * 5 + 60) / 4\n"
      "        @parameters[4, level] = (level * 5 + 40) / 2\n"
      "        @parameters[5, level] = (level * 5 + 40) / 2\n"
      "      end\n"
      "      @pharmacology = false\n"
      "      @super_guard = false\n"
      "      @two_swords_style = false\n"
#else
      "      @armor1_fix = false\n"
      "      @armor2_fix = false\n"
      "      @armor3_fix = false\n"
      "      @armor4_fix = false\n"
      "      @battler_hue = 0\n"
      "      @battler_name = \"\"\n"
      "      @character_hue = 0\n"
      "      @character_name = \"\"\n"
      "      @exp_basis = 30\n"
      "      @exp_inflation = 30\n"
      "      @final_level = 99\n"
      "      @parameters = Table.new(6, 100)\n"
      "      (1..99).each do|level|\n"
      "        @parameters[0, level] = level * 50 + 500\n"
      "        @parameters[1, level] = level * 50 + 500\n"
      "        @parameters[2, level] = level * 5 + 50\n"
      "        @parameters[3, level] = level * 5 + 50\n"
      "        @parameters[4, level] = level * 5 + 50\n"
      "        @parameters[5, level] = level * 5 + 50\n"
      "      end\n"
      "      @weapon_fix = false\n"
#endif
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Class < BaseItem\n"
      "    attr_accessor :exp_params, :learnings, :params\n"
      "    def initialize\n"
      "      super\n"
      "      @exp_params = [30, 20, 30, 30]\n"
      "      @features << RPG::BaseItem::Feature.new(23, 0, 1)\n"
      "      @features << RPG::BaseItem::Feature.new(22, 0, 0.95)\n"
      "      @features << RPG::BaseItem::Feature.new(22, 1, 0.05)\n"
      "      @features << RPG::BaseItem::Feature.new(22, 2, 0.04)\n"
      "      @features << RPG::BaseItem::Feature.new(41, 1, 0)\n"
      "      @features << RPG::BaseItem::Feature.new(51, 1, 0)\n"
      "      @features << RPG::BaseItem::Feature.new(52, 1, 0)\n"
      "      @learnings = []\n"
      "      @params = Table.new(8, 100)\n"
      "      (1..99).each do|level|\n"
      "        @params[0, level] = level * 50 + 400\n"
      "        @params[1, level] = level * 10 + 80\n"
      "        @params[2, level] = (level * 5 + 60) / 4\n"
      "        @params[3, level] = (level * 5 + 60) / 4\n"
      "        @params[4, level] = (level * 5 + 60) / 4\n"
      "        @params[5, level] = (level * 5 + 60) / 4\n"
      "        @params[6, level] = (level * 5 + 60) / 2\n"
      "        @params[7, level] = (level * 5 + 60) / 2\n"
      "      end\n"
      "    end\n"
      "    def exp_for_level(level)\n"
      "      level = level.to_f\n"
      "      a = @exp_params[0].to_f * (level - 1) ** (0.9 + @exp_params[2].to_f / 250) * level * (level + 1)\n"
      "      b = 6 + level ** 2 / 50 / @exp_params[3].to_f\n"
      "      (a / b + (level - 1) * @exp_params[1].to_f).round.to_i\n"
      "    end\n"
      "    class Learning\n"
      "      attr_accessor :level, :note, :skill_id\n"
      "      def initialize\n"
      "        @level = 1\n"
      "        @note = \"\"\n"
      "        @skill_id = 1\n"
      "      end\n"
      "    end\n"
      "  end\n"
#else
      "  class Class\n"
      "    attr_accessor :armor_set, :element_ranks, :id, :learnings, :name, :position, :state_ranks, :weapon_set\n"
#if RGSS == 2
      "    attr_accessor :skill_name, :skill_name_valid\n"
#endif
      "    def initialize\n"
      "      @armor_set = []\n"
      "      @element_ranks = Table.new(1)\n"
      "      @id = 0\n"
      "      @learnings = []\n"
      "      @name = \"\"\n"
      "      @position = 0\n"
      "      @state_ranks = Table.new(1)\n"
      "      @weapon_set = []\n"
#if RGSS == 2
      "      @skill_name = \"\"\n"
      "      @skill_name_valid = false\n"
#endif
      "    end\n"
      "    class Learning\n"
      "      attr_accessor :level, :skill_id\n"
      "      def initialize\n"
      "        @level = 1\n"
      "        @skill_id = 1\n"
      "      end\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS >= 2
      "  class UsableItem < BaseItem\n"
#if RGSS == 3
      "    def initialize\n"
      "      super\n"
      "      @animation_id = 0\n"
      "      @damage = RPG::UsableItem::Damage.new\n"
      "      @effects = []\n"
      "      @hit_type = 0\n"
      "      @occasion = 0\n"
      "      @repeats = 1\n"
      "      @scope = 0\n"
      "      @speed = 0\n"
      "      @success_rate = 100\n"
      "      @tp_gain = 0\n"
      "    end\n"
      "    attr_accessor :animation_id, :damage, :effects, :hit_type, :occasion, :repeats, :scope, :speed, :success_rate, :tp_gain\n"
      "    def for_opponent?\n"
      "      [1, 2, 3, 4, 5, 6].include?(@scope)\n"
      "    end\n"
      "    def for_friend?\n"
      "      [7, 8, 9, 10, 11].include?(@scope)\n"
      "    end\n"
      "    def for_dead_friend?\n"
      "      [9, 10].include?(@scope)\n"
      "    end\n"
      "    def for_user?\n"
      "      @scope == 11\n"
      "    end\n"
      "    def for_one?\n"
      "      [1, 3, 7, 9, 11].include?(@scope)\n"
      "    end\n"
      "    def for_random?\n"
      "      [3, 4, 5, 6].include?(@scope)\n"
      "    end\n"
      "    def number_of_targets\n"
      "      [0, 0, 0, 1, 2, 3, 4, 0, 0, 0, 0, 0][@scope]\n"
      "    end\n"
      "    def for_all?\n"
      "      [2, 8, 10].include?(@scope)\n"
      "    end\n"
      "    def need_selection?\n"
      "      [1, 7, 9].include?(@scope)\n"
      "    end\n"
      "    def battle_ok?\n"
      "      [0, 1].include?(@occasion)\n"
      "    end\n"
      "    def menu_ok?\n"
      "      [0, 2].include?(@occasion)\n"
      "    end\n"
      "    def certain?\n"
      "      @hit_type == 0\n"
      "    end\n"
      "    def physical?\n"
      "      @hit_type == 1\n"
      "    end\n"
      "    def magical?\n"
      "      @hit_type == 2\n"
      "    end\n"
      "    class Damage\n"
      "      attr_accessor :critical, :element_id, :formula, :type, :variance\n"
      "      def none?\n"
      "        @type == 0\n"
      "      end\n"
      "      def to_hp?\n"
      "        [1, 3, 5].include?(@type)\n"
      "      end\n"
      "      def to_mp?\n"
      "        [2, 4, 6].include?(@type)\n"
      "      end\n"
      "      def recover?\n"
      "        [3, 4].include?(@type)\n"
      "      end\n"
      "      def drain?\n"
      "        [5, 6].include?(@type)\n"
      "      end\n"
      "      def sign\n"
      "        recover? ? -1 : 1\n"
      "      end\n"
      "      def eval(a, b, v)\n"
      "        [Kernel.eval(@formula), 0].max * self.sign rescue 0\n"
      "      end\n"
      "      def initialize\n"
      "        @critical = false\n"
      "        @element_id = 0\n"
      "        @formula = \"0\"\n"
      "        @type = 0\n"
      "        @variance = 20\n"
      "      end\n"
      "    end\n"
      "    class Effect\n"
      "      attr_accessor :code, :data_id, :value1, :value2\n"
      "      def initialize(code = 0, data_id = 0, value1 = 0, value2 = 0)\n"
      "        @code = code\n"
      "        @data_id = data_id\n"
      "        @value1 = value1\n"
      "        @value2 = value2\n"
      "      end\n"
      "    end\n"
#else
      "    attr_accessor :absorb_damage, :animation_id, :atk_f, :base_damage, :common_event_id, :damage_to_mp, :element_set, :ignore_defense, :minus_state_set, :occasion, :physical_attack, :plus_state_set, :scope, :speed, :spi_f, :variance\n"
      "    def initialize\n"
      "      super\n"
      "      @absorb_damage = false\n"
      "      @animation_id = 0\n"
      "      @atk_f = 0\n"
      "      @base_damage = 0\n"
      "      @common_event_id = 0\n"
      "      @damage_to_mp = false\n"
      "      @element_set = []\n"
      "      @ignore_defense = false\n"
      "      @minus_state_set = []\n"
      "      @occasion = 0\n"
      "      @physical_attack = false\n"
      "      @plus_state_set = []\n"
      "      @scope = 0\n"
      "      @speed = 0\n"
      "      @spi_f = 0\n"
      "      @variance = 20\n"
      "    end\n"
      "    def for_opponent?\n"
      "      [1, 2, 3, 4, 5, 6].include?(@scope)\n"
      "    end\n"
      "    def for_friend?\n"
      "      [7, 8, 9, 10, 11].include?(@scope)\n"
      "    end\n"
      "    def for_dead_friend?\n"
      "      [9, 10].include?(@scope)\n"
      "    end\n"
      "    def for_user?\n"
      "      @scope == 11\n"
      "    end\n"
      "    def for_one?\n"
      "      [1, 3, 4, 7, 9, 11].include?(@scope)\n"
      "    end\n"
      "    def for_two?\n"
      "      @scope == 5\n"
      "    end\n"
      "    def for_three?\n"
      "      @scope == 6\n"
      "    end\n"
      "    def for_random?\n"
      "      [4, 5, 6].include?(@scope)\n"
      "    end\n"
      "    def for_all?\n"
      "      [2, 8, 10].include?(@scope)\n"
      "    end\n"
      "    def dual?\n"
      "      @scope == 3\n"
      "    end\n"
      "    def need_selection?\n"
      "      [1, 3, 7, 9].include?(@scope)\n"
      "    end\n"
      "    def battle_ok?\n"
      "      [0, 1].include?(@occasion)\n"
      "    end\n"
      "    def menu_ok?\n"
      "      [0, 2].include?(@occasion)\n"
      "    end\n"
#endif
      "  end\n"
#endif
#if RGSS == 3
      "  class Skill < UsableItem\n"
      "    attr_accessor :message1, :message2, :mp_cost, :required_wtype_id1, :required_wtype_id2, :stype_id, :tp_cost\n"
      "    def initialize\n"
      "      super\n"
      "      @message1 = \"\"\n"
      "      @message2 = \"\"\n"
      "      @mp_cost = 0\n"
      "      @required_wtype_id1 = 0\n"
      "      @required_wtype_id2 = 0\n"
      "      @scope = 1\n"
      "      @stype_id = 1\n"
      "      @tp_cost = 0\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class Skill < UsableItem\n"
      "    attr_accessor :hit, :message1, :message2, :mp_cost\n"
      "    def initialize\n"
      "      super\n"
      "      @hit = 100\n"
      "      @message1 = \"\"\n"
      "      @message2 = \"\"\n"
      "      @mp_cost = 0\n"
      "      @scope = 1\n"
      "    end\n"
      "  end\n"
#else
      "  class Skill\n"
      "    attr_accessor :agi_f, :animation1_id, :animation2_id, :atk_f, :common_event_id, :description, :dex_f, :element_set, :eva_f, :hit, :icon_name, :id, :int_f, :mdef_f, :menu_se, :minus_state_set, :name, :occasion, :pdef_f, :plus_state_set, :power, :scope, :sp_cost, :str_f, :variance\n"
      "    def initialize\n"
      "      @agi_f = 0\n"
      "      @animation1_id = 0\n"
      "      @animation2_id = 0\n"
      "      @atk_f = 0\n"
      "      @common_event_id = 0\n"
      "      @description = \"\"\n"
      "      @dex_f = 0\n"
      "      @element_set = []\n"
      "      @eva_f = 0\n"
      "      @hit = 100\n"
      "      @icon_name = \"\"\n"
      "      @id = 0\n"
      "      @int_f = 100\n"
      "      @mdef_f = 100\n"
      "      @menu_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @minus_state_set = []\n"
      "      @name = \"\"\n"
      "      @occasion = 1\n"
      "      @pdef_f = 0\n"
      "      @plus_state_set = []\n"
      "      @power = 0\n"
      "      @scope = 0\n"
      "      @sp_cost = 0\n"
      "      @str_f = 0\n"
      "      @variance = 15\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Item < UsableItem\n"
      "    attr_accessor :consumable, :itype_id, :price\n"
      "    def key_item?\n"
      "      @itype_id == 2\n"
      "    end\n"
      "    def initialize\n"
      "      super\n"
      "      @consumable = true\n"
      "      @itype_id = 1\n"
      "      @price = 0\n"
      "      @scope = 7\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class Item < UsableItem\n"
      "    attr_accessor :consumable, :hp_recovery, :hp_recovery_rate, :mp_recovery, :mp_recovery_rate, :parameter_points, :parameter_type, :price\n"
      "    def initialize\n"
      "      super\n"
      "      @consumable = true\n"
      "      @hp_recovery = 0\n"
      "      @hp_recovery_rate = 0\n"
      "      @mp_recovery = 0\n"
      "      @mp_recovery_rate = 0\n"
      "      @parameter_points = 0\n"
      "      @parameter_type = 0\n"
      "      @price = 0\n"
      "      @scope = 7\n"
      "    end\n"
      "  end\n"
#else
      "  class Item\n"
      "    attr_accessor :animation1_id, :animation2_id, :common_event_id, :consumable, :description, :element_set, :hit, :icon_name, :id, :mdef_f, :menu_se, :minus_state_set, :name, :occasion, :parameter_points, :parameter_type, :pdef_f, :plus_state_set, :price, :recover_hp, :recover_hp_rate, :recover_sp, :recover_sp_rate, :scope, :variance\n"
      "    def initialize\n"
      "      @animation1_id = 0\n"
      "      @animation2_id = 0\n"
      "      @common_event_id = 0\n"
      "      @consumable = true\n"
      "      @description = \"\"\n"
      "      @element_set = []\n"
      "      @hit = 100\n"
      "      @icon_name = \"\"\n"
      "      @id = 0\n"
      "      @mdef_f = 0\n"
      "      @menu_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @minus_state_set = []\n"
      "      @name = \"\"\n"
      "      @occasion = 0\n"
      "      @parameter_points = 0\n"
      "      @parameter_type = 0\n"
      "      @pdef_f = 0\n"
      "      @plus_state_set = []\n"
      "      @price = 0\n"
      "      @recover_hp = 0\n"
      "      @recover_hp_rate = 0\n"
      "      @recover_sp = 0\n"
      "      @recover_sp_rate = 0\n"
      "      @scope = 0\n"
      "      @variance = 0\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class EquipItem < BaseItem\n"
      "    attr_accessor :etype_id, :params, :price\n"
      "    def initialize\n"
      "      super\n"
      "      @etype_id = 0\n"
      "      @params = [0, 0, 0, 0, 0, 0, 0, 0]\n"
      "      @price = 0\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Weapon < EquipItem\n"
      "    attr_accessor :animation_id, :wtype_id\n"
      "    def performance\n"
      "      @params[2] + @params[4] + @params.inject(&:+)\n"
      "    end\n"
      "    def initialize\n"
      "      super\n"
      "      @animation_id = 0\n"
      "      @wtype_id = 0\n"
      "      @features << RPG::BaseItem::Feature.new(31, 1, 0)\n"
      "      @features << RPG::BaseItem::Feature.new(22, 0, 0)\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class Weapon < BaseItem\n"
      "    attr_accessor :agi, :animation_id, :atk, :critical_bonus, :def, :dual_attack, :element_set, :fast_attack, :hit, :price, :spi, :state_set, :two_handed\n"
      "    def initialize\n"
      "      super\n"
      "      @agi = 0\n"
      "      @animation_id = 0\n"
      "      @atk = 0\n"
      "      @critical_bonus = false\n"
      "      @def = 0\n"
      "      @dual_attack = false\n"
      "      @element_set = []\n"
      "      @fast_attack = false\n"
      "      @hit = 95\n"
      "      @price = 0\n"
      "      @spi = 0\n"
      "      @state_set = []\n"
      "      @two_handed = false\n"
      "    end\n"
      "  end\n"
#else
      "  class Weapon\n"
      "    attr_accessor :agi_plus, :animation1_id, :animation2_id, :atk, :description, :dex_plus, :element_set, :icon_name, :id, :int_plus, :mdef, :minus_state_set, :name, :pdef, :plus_state_set, :price, :str_plus\n"
      "    def initialize\n"
      "      @agi_plus = 0\n"
      "      @animation1_id = 0\n"
      "      @animation2_id = 0\n"
      "      @atk = 0\n"
      "      @description = \"\"\n"
      "      @dex_plus = 0\n"
      "      @element_set = []\n"
      "      @icon_name = \"\"\n"
      "      @id = 0\n"
      "      @int_plus = 0\n"
      "      @mdef = 0\n"
      "      @minus_state_set = []\n"
      "      @name = \"\"\n"
      "      @pdef = 0\n"
      "      @plus_state_set = []\n"
      "      @price = 0\n"
      "      @str_plus = 0\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Armor < EquipItem\n"
      "    attr_accessor :atype_id\n"
      "    def performance\n"
      "      @params[3] + @params[5] + @params.inject(&:+)\n"
      "    end\n"
      "    def initialize\n"
      "      super\n"
      "      @atype_id = 0\n"
      "      @etype_id = 1\n"
      "      @features << RPG::BaseItem::Feature.new(22, 1, 0)\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class Armor < BaseItem\n"
      "    attr_accessor :agi, :atk, :auto_hp_recover, :def, :double_exp_gain, :element_set, :eva, :half_mp_cost, :kind, :prevent_critical, :price, :spi, :state_set\n"
      "    def initialize\n"
      "      super\n"
      "      @agi = 0\n"
      "      @atk = 0\n"
      "      @auto_hp_recover = false\n"
      "      @def = 0\n"
      "      @double_exp_gain = false\n"
      "      @element_set = []\n"
      "      @eva = 0\n"
      "      @half_mp_cost = false\n"
      "      @kind = 0\n"
      "      @prevent_critical = false\n"
      "      @price = 0\n"
      "      @spi = 0\n"
      "      @state_set = []\n"
      "    end\n"
      "  end\n"
#else
      "  class Armor\n"
      "    attr_accessor :agi_plus, :auto_state_id, :description, :dex_plus, :eva, :guard_element_set, :guard_state_set, :icon_name, :id, :int_plus, :kind, :mdef, :name, :pdef, :price, :str_plus\n"
      "    def initialize\n"
      "      @agi_plus = 0\n"
      "      @auto_state_id = 0\n"
      "      @description = \"\"\n"
      "      @dex_plus = 0\n"
      "      @eva = 0\n"
      "      @guard_element_set = []\n"
      "      @guard_state_set = []\n"
      "      @icon_name = \"\"\n"
      "      @id = 0\n"
      "      @int_plus = 0\n"
      "      @kind = 0\n"
      "      @mdef = 0\n"
      "      @name = \"\"\n"
      "      @pdef = 0\n"
      "      @price = 0\n"
      "      @str_plus = 0\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Enemy < BaseItem\n"
      "    attr_accessor :actions, :battler_hue, :battler_name, :drop_items, :exp, :gold, :params\n"
      "    def initialize\n"
      "      super\n"
      "      @actions = [RPG::Enemy::Action.new]\n"
      "      @battler_hue = 0\n"
      "      @battler_name = \"\"\n"
      "      @drop_items = [RPG::Enemy::DropItem.new, RPG::Enemy::DropItem.new, RPG::Enemy::DropItem.new]\n"
      "      @exp = 0\n"
      "      @features << RPG::BaseItem::Feature.new(22, 0, 0.95)\n"
      "      @features << RPG::BaseItem::Feature.new(22, 1, 0.05)\n"
      "      @features << RPG::BaseItem::Feature.new(31, 1, 0)\n"
      "      @gold = 0\n"
      "      @params = [100, 0, 10, 10, 10, 10, 10, 10]\n"
      "    end\n"
      "    class Action\n"
      "      attr_accessor :condition_param1, :condition_param2, :condition_type, :rating, :skill_id\n"
      "      def initialize\n"
      "        @condition_param1 = 0\n"
      "        @condition_param2 = 0\n"
      "        @condition_type = 0\n"
      "        @rating = 5\n"
      "        @skill_id = 1\n"
      "      end\n"
      "    end\n"
      "    class DropItem\n"
      "      attr_accessor :data_id, :denominator, :kind\n"
      "      def initialize\n"
      "        @data_id = 1\n"
      "        @denominator = 1\n"
      "        @kind = 0\n"
      "      end\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class Enemy\n"
      "    attr_accessor :actions, :agi, :atk, :battler_hue, :battler_name, :def, :drop_item1, :drop_item2, :element_ranks, :eva, :exp, :gold, :has_critical, :hit, :id, :levitate, :maxhp, :maxmp, :name, :note, :spi, :state_ranks\n"
      "    def initialize\n"
      "      @actions = [RPG::Enemy::Action.new]\n"
      "      @agi = 10\n"
      "      @atk = 10\n"
      "      @battler_hue = 0\n"
      "      @battler_name = \"\"\n"
      "      @def = 10\n"
      "      @drop_item1 = RPG::Enemy::DropItem.new\n"
      "      @drop_item2 = RPG::Enemy::DropItem.new\n"
      "      @element_ranks = Table.new(1)\n"
      "      @eva = 5\n"
      "      @exp = 0\n"
      "      @gold = 0\n"
      "      @has_critical = false\n"
      "      @hit = 95\n"
      "      @id = 0\n"
      "      @levitate = false\n"
      "      @maxhp = 10\n"
      "      @maxmp = 10\n"
      "      @name = \"\"\n"
      "      @note = \"\"\n"
      "      @spi = 10\n"
      "      @state_ranks = Table.new(1)\n"
      "    end\n"
      "    class Action\n"
      "      attr_accessor :basic, :condition_param1, :condition_param2, :condition_type, :kind, :rating, :skill_id\n"
      "      def skill?\n"
      "        @kind == 1\n"
      "      end\n"
      "      def initialize\n"
      "        @basic = 0\n"
      "        @condition_param1 = 0\n"
      "        @condition_param2 = 0\n"
      "        @condition_type = 0\n"
      "        @kind = 0\n"
      "        @rating = 5\n"
      "        @skill_id = 1\n"
      "      end\n"
      "    end\n"
      "    class DropItem\n"
      "      attr_accessor :armor_id, :denominator, :item_id, :kind, :weapon_id\n"
      "      def initialize\n"
      "        @armor_id = 1\n"
      "        @denominator = 1\n"
      "        @item_id = 1\n"
      "        @kind = 0\n"
      "        @weapon_id = 1\n"
      "      end\n"
      "    end\n"
      "  end\n"
#else
      "  class Enemy\n"
      "    attr_accessor :actions, :agi, :animation1_id, :animation2_id, :armor_id, :atk, :battler_hue, :battler_name, :dex, :element_ranks, :eva, :exp, :gold, :id, :int, :item_id, :maxhp, :maxsp, :mdef, :name, :pdef, :state_ranks, :str, :treasure_prob, :weapon_id\n"
      "    def initialize\n"
      "      @actions = [RPG::Enemy::Action.new]\n"
      "      @agi = 50\n"
      "      @animation1_id = 0\n"
      "      @animation2_id = 0\n"
      "      @armor_id = 0\n"
      "      @atk = 100\n"
      "      @battler_hue = 0\n"
      "      @battler_name = \"\"\n"
      "      @dex = 50\n"
      "      @element_ranks = Table.new(1)\n"
      "      @eva = 0\n"
      "      @exp = 0\n"
      "      @gold = 0\n"
      "      @id = 0\n"
      "      @int = 50\n"
      "      @item_id = 0\n"
      "      @maxhp = 500\n"
      "      @maxsp = 500\n"
      "      @mdef = 100\n"
      "      @name = \"\"\n"
      "      @pdef = 100\n"
      "      @state_ranks = Table.new(1)\n"
      "      @str = 50\n"
      "      @treasure_prob = 100\n"
      "      @weapon_id = 0\n"
      "    end\n"
      "    class Action\n"
      "      attr_accessor :basic, :condition_hp, :condition_level, :condition_switch_id, :condition_turn_a, :condition_turn_b, :kind, :rating, :skill_id\n"
      "      def initialize\n"
      "        @basic = 0\n"
      "        @condition_hp = 100\n"
      "        @condition_level = 1\n"
      "        @condition_switch_id = 0\n"
      "        @condition_turn_a = 0\n"
      "        @condition_turn_b = 1\n"
      "        @kind = 0\n"
      "        @rating = 5\n"
      "        @skill_id = 1\n"
      "      end\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class State < BaseItem\n"
      "    attr_accessor :auto_removal_timing, :chance_by_damage, :max_turns, :message1, :message2, :message3, :message4, :min_turns, :priority, :remove_at_battle_end, :remove_by_damage, :remove_by_restriction, :remove_by_walking, :restriction, :steps_to_remove\n"
      "    def initialize\n"
      "      super\n"
      "      @auto_removal_timing = 0\n"
      "      @chance_by_damage = 100\n"
      "      @max_turns = 1\n"
      "      @message1 = \"\"\n"
      "      @message2 = \"\"\n"
      "      @message3 = \"\"\n"
      "      @message4 = \"\"\n"
      "      @min_turns = 1\n"
      "      @priority = 50\n"
      "      @remove_at_battle_end = false\n"
      "      @remove_by_damage = false\n"
      "      @remove_by_restriction = false\n"
      "      @remove_by_walking = false\n"
      "      @restriction = 0\n"
      "      @steps_to_remove = 100\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class State\n"
      "    attr_accessor :id, :name, :icon_index, :restriction, :priority, :atk_rate, :def_rate, :spi_rate, :agi_rate, :nonresistance, :offset_by_opposite, :slip_damage, :reduce_hit_ratio, :battle_only, :release_by_damage, :hold_turn, :auto_release_prob, :message1, :message2, :message3, :message4, :element_set, :state_set, :note\n"
      "    def initialize\n"
      "      @agi_rate = 100\n"
      "      @atk_rate = 100\n"
      "      @auto_release_prob = 0\n"
      "      @battle_only = true\n"
      "      @def_rate = 100\n"
      "      @element_set = []\n"
      "      @hold_turn = 0\n"
      "      @icon_index = 0\n"
      "      @id = 0\n"
      "      @message1 = \"\"\n"
      "      @message2 = \"\"\n"
      "      @message3 = \"\"\n"
      "      @message4 = \"\"\n"
      "      @name = \"\"\n"
      "      @nonresistance = false\n"
      "      @note = \"\"\n"
      "      @offset_by_opposite = false\n"
      "      @priority = 5\n"
      "      @reduce_hit_ratio = false\n"
      "      @release_by_damage = false\n"
      "      @restriction = 0\n"
      "      @slip_damage = false\n"
      "      @spi_rate = 100\n"
      "      @state_set = []\n"
      "    end\n"
      "  end\n"
#elif RGSS == 1
      "  class State\n"
      "    attr_accessor :agi_rate, :animation_id, :atk_rate, :auto_release_prob, :battle_only, :cant_evade, :cant_get_exp, :dex_rate, :eva, :guard_element_set, :hit_rate, :hold_turn, :id, :int_rate, :maxhp_rate, :maxsp_rate, :mdef_rate, :minus_state_set, :name, :nonresistance, :pdef_rate, :plus_state_set, :rating, :restriction, :shock_release_prob, :slip_damage, :str_rate, :zero_hp\n"
      "    def initialize\n"
      "      @agi_rate = 100\n"
      "      @animation_id = 0\n"
      "      @atk_rate = 100\n"
      "      @auto_release_prob = 0\n"
      "      @battle_only = true\n"
      "      @cant_evade = false\n"
      "      @cant_get_exp = false\n"
      "      @dex_rate = 100\n"
      "      @eva = 0\n"
      "      @guard_element_set = []\n"
      "      @hit_rate = 100\n"
      "      @hold_turn = 0\n"
      "      @id = 0\n"
      "      @int_rate = 100\n"
      "      @maxhp_rate = 100\n"
      "      @maxsp_rate = 100\n"
      "      @mdef_rate = 100\n"
      "      @minus_state_set = []\n"
      "      @name = \"\"\n"
      "      @nonresistance = false\n"
      "      @pdef_rate = 100\n"
      "      @plus_state_set = []\n"
      "      @rating = 5\n"
      "      @restriction = 0\n"
      "      @shock_release_prob = 0\n"
      "      @slip_damage = false\n"
      "      @str_rate = 100\n"
      "      @zero_hp = false\n"
      "    end\n"
      "  end\n"
#endif
      "  class Troop\n"
      "    attr_accessor :id, :name, :members, :pages\n"
      "    def initialize\n"
      "      @id = 0\n"
      "      @members = []\n"
      "      @name = \"\"\n"
      "      @pages = [RPG::Troop::Page.new]\n"
      "    end\n"
      "    class Member\n"
      "      attr_accessor :enemy_id, :hidden, :x, :y\n"
#if RGSS <= 2
      "      attr_accessor :immortal\n"
#endif
      "      def initialize\n"
      "        @enemy_id = 1\n"
      "        @hidden = false\n"
      "        @x = 0\n"
      "        @y = 0\n"
#if RGSS <= 2
      "        @immortal = false\n"
#endif
      "      end\n"
      "    end\n"
      "    class Page\n"
      "      attr_accessor :condition, :list, :span\n"
      "      def initialize\n"
      "        @condition = RPG::Troop::Page::Condition.new\n"
      "        @list = [RPG::EventCommand.new]\n"
      "        @span = 0\n"
      "      end\n"
      "      class Condition\n"
#if RGSS >= 2
      "        attr_accessor :turn_ending\n"
#endif
      "        attr_accessor :actor_hp, :actor_id, :actor_valid, :enemy_hp, :enemy_index, :enemy_valid, :switch_id, :switch_valid, :turn_a, :turn_b, :turn_valid\n"
      "        def initialize\n"
      "          @actor_hp = 50\n"
      "          @actor_id = 1\n"
      "          @actor_valid = false\n"
      "          @enemy_hp = 50\n"
      "          @enemy_index = 0\n"
      "          @enemy_valid = false\n"
      "          @switch_id = 1\n"
      "          @switch_valid = false\n"
      "          @turn_a = 0\n"
      "          @turn_b = 0\n"
      "          @turn_valid = false\n"
#if RGSS >= 2
      "          @turn_ending = false\n"
#endif
      "        end\n"
      "      end\n"
      "    end\n"
      "  end\n"
      "  class Animation\n"
      "    attr_accessor :frame_max, :frames, :id, :name, :position, :timings\n"
#if RGSS >= 2
      "    attr_accessor :animation1_hue, :animation1_name, :animation2_hue, :animation2_name\n"
#else
      "    attr_accessor :animation_hue, :animation_name\n"
#endif
#if RGSS == 3
      "    def to_screen?\n"
      "      @position == 3\n"
      "    end\n"
#endif
      "    def initialize\n"
#if RGSS >= 2
      "      @animation1_hue = 0\n"
      "      @animation1_name = \"\"\n"
      "      @animation2_hue = 0\n"
      "      @animation2_name = \"\"\n"
#else
      "      @animation_hue = 0\n"
      "      @animation_name = \"\"\n"
#endif
      "      @frame_max = 1\n"
      "      @frames = [RPG::Animation::Frame.new]\n"
      "      @id = 0\n"
      "      @name = \"\"\n"
      "      @position = 1\n"
      "      @timings = []\n"
      "    end\n"
      "    class Frame\n"
      "      attr_accessor :cell_data, :cell_max\n"
      "      def initialize\n"
      "        @cell_data = Table.new(0, 0)\n"
      "        @cell_max = 0\n"
      "      end\n"
      "    end\n"
      "    class Timing\n"
      "      attr_accessor :flash_color, :flash_duration, :flash_scope, :frame, :se\n"
#if RGSS == 1
      "      attr_accessor :condition\n"
#endif
      "      def initialize\n"
      "        @flash_color = Color.new(255, 255, 255, 255)\n"
      "        @flash_duration = 5\n"
      "        @flash_scope = 0\n"
      "        @frame = 0\n"
#if RGSS >= 2
      "        @se = RPG::SE.new(\"\", 80)\n"
#else
      "        @se = RPG::AudioFile.new(\"\", 80)\n"
      "        @condition = 0\n"
#endif
      "      end\n"
      "    end\n"
      "  end\n"
#if RGSS == 3
      "  class Tileset\n"
      "    attr_accessor :flags, :id, :mode, :name, :note, :tileset_names\n"
      "    def initialize\n"
      "      @flags = Table.new(0x2000)\n"
      "      @flags[0] = 0x10\n"
      "      (0x0800...0x0B00).each {|i| @flags[i] = 0x0f }\n"
      "      (0x1100...0x2000).each {|i| @flags[i] = 0x0f }\n"
      "      @id = 0\n"
      "      @mode = 1\n"
      "      @name = \"\"\n"
      "      @note = \"\"\n"
      "      @tileset_names = [\"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\"]\n"
      "    end\n"
      "  end\n"
#elif RGSS == 1
      "  class Tileset\n"
      "    attr_accessor :autotile_names, :battleback_name, :fog_blend_type, :fog_hue, :fog_name, :fog_opacity, :fog_sx, :fog_sy, :fog_zoom, :id, :name, :panorama_hue, :panorama_name, :passages, :priorities, :terrain_tags, :tileset_name\n"
      "    def initialize\n"
      "      @autotile_names = [\"\", \"\", \"\", \"\", \"\", \"\", \"\"]\n"
      "      @battleback_name = \"\"\n"
      "      @fog_blend_type = 0\n"
      "      @fog_hue = 0\n"
      "      @fog_name = \"\"\n"
      "      @fog_opacity = 64\n"
      "      @fog_sx = 0\n"
      "      @fog_sy = 0\n"
      "      @fog_zoom = 200\n"
      "      @id = 0\n"
      "      @name = \"\"\n"
      "      @panorama_hue = 0\n"
      "      @panorama_name = \"\"\n"
      "      @passages = Table.new(384)\n"
      "      @priorities = Table.new(384)\n"
      "      @priorities[0] = 5\n"
      "      @terrain_tags = Table.new(384)\n"
      "      @tileset_name = \"\"\n"
      "    end\n"
      "  end\n"
#endif
      "  class CommonEvent\n"
      "    attr_accessor :id, :name, :trigger, :switch_id, :list\n"
#if RGSS == 3
      "    def autorun?\n"
      "      @trigger == 1\n"
      "    end\n"
      "    def parallel?\n"
      "      @trigger == 2\n"
      "    end\n"
#endif
      "    def initialize\n"
      "      @id = 0\n"
      "      @list = [RPG::EventCommand.new]\n"
      "      @name = \"\"\n"
      "      @switch_id = 1\n"
      "      @trigger = 0\n"
      "    end\n"
      "  end\n"
      "  class System\n"
#if RGSS >= 2
      "    attr_accessor :airship, :boat, :game_title, :ship, :sounds, :terms, :version_id\n"
#endif
      "    attr_accessor :battle_bgm, :battle_end_me, :battler_hue, :battler_name, :edit_map_id, :elements, :gameover_me, :party_members, :start_map_id, :start_x, :start_y, :switches, :test_battlers, :test_troop_id, :title_bgm, :variables\n"
#if RGSS == 3
      "    attr_accessor :armor_types, :battleback1_name, :battleback2_name, :currency_unit, :japanese, :opt_display_tp, :opt_draw_title, :opt_extra_exp, :opt_floor_death, :opt_followers, :opt_slip_death, :opt_transparent, :opt_use_midi, :skill_types, :title1_name, :title2_name, :weapon_types, :window_tone\n"
#elif RGSS == 2
      "    attr_accessor :passages\n"
#else
      "    attr_accessor :actor_collapse_se, :battle_start_se, :battle_transition, :battleback_name, :buzzer_se, :cancel_se, :cursor_se, :decision_se, :enemy_collapse_se, :equip_se, :escape_se, :gameover_name, :load_se, :magic_number, :save_se, :shop_se, :title_name, :windowskin_name, :words\n"
#endif
      "    def initialize\n"
#if RGSS == 3
      "      @airship = RPG::System::Vehicle.new\n"
      "      @armor_types = [nil, \"\"]\n"
      "      @battle_bgm = RPG::BGM.new\n"
      "      @battle_end_me = RPG::ME.new\n"
      "      @battleback1_name = \"\"\n"
      "      @battleback2_name = \"\"\n"
      "      @battler_hue = 0\n"
      "      @battler_name = \"\"\n"
      "      @boat = RPG::System::Vehicle.new\n"
      "      @currency_unit = \"\"\n"
      "      @edit_map_id = 1\n"
      "      @elements = [nil, \"\"]\n"
      "      @game_title = \"\"\n"
      "      @gameover_me = RPG::ME.new\n"
      "      @japanese = true\n"
      "      @opt_display_tp = true\n"
      "      @opt_draw_title = true\n"
      "      @opt_extra_exp = false\n"
      "      @opt_floor_death = false\n"
      "      @opt_followers = true\n"
      "      @opt_slip_death = false\n"
      "      @opt_transparent = false\n"
      "      @opt_use_midi = false\n"
      "      @party_members = [1]\n"
      "      @ship = RPG::System::Vehicle.new\n"
      "      @skill_types = [nil, \"\"]\n"
      "      @sounds = Array.new(24) { RPG::SE.new }\n"
      "      @start_map_id = 1\n"
      "      @start_x = 0\n"
      "      @start_y = 0\n"
      "      @switches = [nil, \"\"]\n"
      "      @terms = RPG::System::Terms.new\n"
      "      @test_battlers = []\n"
      "      @test_troop_id = 1\n"
      "      @title1_name = \"\"\n"
      "      @title2_name = \"\"\n"
      "      @title_bgm = RPG::BGM.new\n"
      "      @variables = [nil, \"\"]\n"
      "      @version_id = 0\n"
      "      @weapon_types = [nil, \"\"]\n"
      "      @window_tone = Tone.new(0, 0, 0, 0)\n"
#elif RGSS == 2
      "      @airship = RPG::System::Vehicle.new\n"
      "      @battle_bgm = RPG::BGM.new\n"
      "      @battle_end_me = RPG::ME.new\n"
      "      @battler_hue = 0\n"
      "      @battler_name = \"\"\n"
      "      @boat = RPG::System::Vehicle.new\n"
      "      @edit_map_id = 1\n"
      "      @elements = [nil, \"\"]\n"
      "      @game_title = \"\"\n"
      "      @gameover_me = RPG::ME.new\n"
      "      @party_members = [1]\n"
      "      @passages = Table.new(8192)\n"
      "      @ship = RPG::System::Vehicle.new\n"
      "      @sounds = Array.new(20) { RPG::SE.new }\n"
      "      @start_map_id = 1\n"
      "      @start_x = 0\n"
      "      @start_y = 0\n"
      "      @switches = [nil, \"\"]\n"
      "      @terms = RPG::System::Terms.new\n"
      "      @test_battlers = []\n"
      "      @test_troop_id = 1\n"
      "      @title_bgm = RPG::BGM.new\n"
      "      @variables = [nil, \"\"]\n"
      "      @version_id = 0\n"
#else
      "      @actor_collapse_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @battle_bgm = RPG::AudioFile.new\n"
      "      @battle_end_me = RPG::AudioFile.new\n"
      "      @battle_start_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @battle_transition = \"\"\n"
      "      @battleback_name = \"\"\n"
      "      @battler_hue = 0\n"
      "      @battler_name = \"\"\n"
      "      @buzzer_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @cancel_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @cursor_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @decision_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @edit_map_id = 1\n"
      "      @elements = [nil, \"\"]\n"
      "      @enemy_collapse_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @equip_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @escape_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @gameover_me = RPG::AudioFile.new\n"
      "      @gameover_name = \"\"\n"
      "      @load_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @magic_number = 0\n"
      "      @party_members = [1]\n"
      "      @save_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @shop_se = RPG::AudioFile.new(\"\", 80)\n"
      "      @start_map_id = 1\n"
      "      @start_x = 0\n"
      "      @start_y = 0\n"
      "      @switches = [nil, \"\"]\n"
      "      @test_battlers = []\n"
      "      @test_troop_id = 1\n"
      "      @title_bgm = RPG::AudioFile.new\n"
      "      @title_name = \"\"\n"
      "      @variables = [nil, \"\"]\n"
      "      @windowskin_name = \"\"\n"
      "      @words = RPG::System::Words.new\n"
#endif
      "    end\n"
#if RGSS == 3
      "    class Terms\n"
      "      attr_accessor :basic, :commands, :etypes, :params\n"
#elif RGSS == 2
      "    class Terms\n"
      "      attr_accessor :agi, :armor1, :armor2, :armor3, :armor4, :atk, :attack, :equip, :gold, :guard, :hp, :item, :skill, :weapon\n"
      "      attr_accessor :cancel, :continue, :def, :escape, :fight, :game_end, :hp_a, :level, :level_a, :mp, :mp_a, :new_game, :save, :shutdown, :spi, :status, :to_title, :weapon1, :weapon2\n"
#else
      "    class Words\n"
      "      attr_accessor :agi, :armor1, :armor2, :armor3, :armor4, :atk, :attack, :equip, :gold, :guard, :hp, :item, :skill, :weapon\n"
      "      attr_accessor :dex, :int, :mdef, :pdef, :sp, :str\n"
#endif
      "      def initialize\n"
#if RGSS == 3
      "        @basic = [\"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\"]\n"
      "        @commands = [\"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\"]\n"
      "        @etypes = [\"\", \"\", \"\", \"\", \"\"]\n"
      "        @params = [\"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\"]\n"
#elif RGSS == 2
      "        @agi = \"\"\n"
      "        @armor1 = \"\"\n"
      "        @armor2 = \"\"\n"
      "        @armor3 = \"\"\n"
      "        @armor4 = \"\"\n"
      "        @atk = \"\"\n"
      "        @attack = \"\"\n"
      "        @cancel = \"\"\n"
      "        @continue = \"\"\n"
      "        @def = \"\"\n"
      "        @equip = \"\"\n"
      "        @escape = \"\"\n"
      "        @fight = \"\"\n"
      "        @game_end = \"\"\n"
      "        @gold = \"\"\n"
      "        @guard = \"\"\n"
      "        @hp = \"\"\n"
      "        @hp_a = \"\"\n"
      "        @item = \"\"\n"
      "        @level = \"\"\n"
      "        @level_a = \"\"\n"
      "        @mp = \"\"\n"
      "        @mp_a = \"\"\n"
      "        @new_game = \"\"\n"
      "        @save = \"\"\n"
      "        @shutdown = \"\"\n"
      "        @skill = \"\"\n"
      "        @spi = \"\"\n"
      "        @status = \"\"\n"
      "        @to_title = \"\"\n"
      "        @weapon1 = \"\"\n"
      "        @weapon2 = \"\"\n"
      "        @weapon = \"\"\n"
#else
      "        @agi = \"\"\n"
      "        @armor1 = \"\"\n"
      "        @armor2 = \"\"\n"
      "        @armor3 = \"\"\n"
      "        @armor4 = \"\"\n"
      "        @atk = \"\"\n"
      "        @attack = \"\"\n"
      "        @dex = \"\"\n"
      "        @equip = \"\"\n"
      "        @gold = \"\"\n"
      "        @guard = \"\"\n"
      "        @hp = \"\"\n"
      "        @int = \"\"\n"
      "        @item = \"\"\n"
      "        @mdef = \"\"\n"
      "        @pdef = \"\"\n"
      "        @skill = \"\"\n"
      "        @sp = \"\"\n"
      "        @str = \"\"\n"
      "        @weapon = \"\"\n"
#endif
      "      end\n"
      "    end\n"
      "    class TestBattler\n"
      "      attr_accessor :actor_id, :level\n"
#if RGSS == 3
      "      attr_accessor :equips\n"
#else
      "      attr_accessor :armor1_id, :armor2_id, :armor3_id, :armor4_id, :weapon_id\n"
#endif
      "      def initialize\n"
      "        @actor_id = 1\n"
      "        @level = 1\n"
#if RGSS == 3
      "        @equips = [0, 0, 0, 0, 0]\n"
#else
      "        @armor1_id = 0\n"
      "        @armor2_id = 0\n"
      "        @armor3_id = 0\n"
      "        @armor4_id = 0\n"
      "        @weapon_id = 0\n"
#endif
      "      end\n"
      "    end\n"
#if RGSS >= 2
      "    class Vehicle\n"
      "      attr_accessor :bgm, :character_index, :character_name, :start_map_id, :start_x, :start_y\n"
      "      def initialize\n"
      "        @bgm = RPG::BGM.new\n"
      "        @character_index = 0\n"
      "        @character_name = \"\"\n"
      "        @start_map_id = 0\n"
      "        @start_x = 0\n"
      "        @start_y = 0\n"
      "      end\n"
      "    end\n"
#endif
      "  end\n"
      "  class AudioFile\n"
      "    attr_accessor :name, :pitch, :volume\n"
      "    def initialize(name = \"\", volume = 100, pitch = 100)\n"
      "      @name = name\n"
      "      @pitch = pitch\n"
      "      @volume = volume\n"
      "    end\n"
      "  end\n"
#if RGSS >= 2
      "  class BGM < AudioFile\n"
#if RGSS == 3
      "    attr_accessor :pos\n"
      "    def replay\n"
      "      play(@pos)\n"
      "    end\n"
      "    def play(pos=0)\n"
      "      if @name == \"\"\n"
      "        Audio.bgm_stop\n"
      "        @@last = BGM.new\n"
      "      else\n"
      "        Audio.bgm_play(\"Audio/BGM/#@name\", @volume, @pitch, pos)\n"
      "        @@last = self.clone\n"
      "      end\n"
      "    end\n"
#else
      "    def play\n"
      "      if @name == \"\"\n"
      "        Audio.bgm_stop\n"
      "        @@last = BGM.new\n"
      "      else\n"
      "        Audio.bgm_play(\"Audio/BGM/#@name\", @volume, @pitch)\n"
      "        @@last = self\n"
      "      end\n"
      "    end\n"
#endif
      "    def self.last\n"
#if RGSS == 3
      "      @@last.pos = Audio.bgm_pos\n"
#endif
      "      @@last\n"
      "    end\n"
      "    def self.stop\n"
      "      Audio.bgm_stop\n"
      "      @@last = BGM.new\n"
      "    end\n"
      "    def self.fade(time)\n"
      "      Audio.bgm_fade(time)\n"
      "      @@last = BGM.new\n"
      "    end\n"
      "    def initialize(name = \"\", volume = 100, pitch = 100)\n"
      "      super(name, volume, pitch)\n"
      "    end\n"
      "    @@last = BGM.new\n"
      "  end\n"
      "  class BGS < AudioFile\n"
#if RGSS == 3
      "    attr_accessor :pos\n"
      "    def replay\n"
      "      play(@pos)\n"
      "    end\n"
      "    def play(pos=0)\n"
      "      if @name == \"\"\n"
      "        Audio.bgs_stop\n"
      "        @@last = BGS.new\n"
      "      else\n"
      "        Audio.bgs_play(\"Audio/BGS/#@name\", @volume, @pitch, pos)\n"
      "        @@last = self.clone\n"
      "      end\n"
      "    end\n"
#else
      "    def play\n"
      "      if @name == \"\"\n"
      "        Audio.bgs_stop\n"
      "        @@last = BGS.new\n"
      "      else\n"
      "        Audio.bgs_play(\"Audio/BGS/#@name\", @volume, @pitch)\n"
      "        @@last = self\n"
      "      end\n"
      "    end\n"
#endif
      "    def self.last\n"
#if RGSS == 3
      "      @@last.pos = Audio.bgs_pos\n"
#endif
      "      @@last\n"
      "    end\n"
      "    def self.stop\n"
      "      Audio.bgs_stop\n"
      "      @@last = BGS.new\n"
      "    end\n"
      "    def self.fade(time)\n"
      "      Audio.bgs_fade(time)\n"
      "      @@last = BGS.new\n"
      "    end\n"
      "    def initialize(name = \"\", volume = 100, pitch = 100)\n"
      "      super(name, volume, pitch)\n"
      "    end\n"
      "    @@last = BGS.new\n"
      "  end\n"
      "  class ME < AudioFile\n"
      "    def play\n"
      "      if @name == \"\"\n"
      "        Audio.me_stop\n"
      "      else\n"
      "        Audio.me_play(\"Audio/ME/#@name\", @volume, @pitch)\n"
      "      end\n"
      "    end\n"
      "    def self.stop\n"
      "      Audio.me_stop\n"
      "    end\n"
      "    def self.fade(time)\n"
      "      Audio.me_fade(time)\n"
      "    end\n"
      "    def initialize(name = \"\", volume = 100, pitch = 100)\n"
      "      super(name, volume, pitch)\n"
      "    end\n"
      "  end\n"
      "  class SE < AudioFile\n"
      "    def play\n"
      "      if @name != \"\"\n"
      "        Audio.se_play(\"Audio/SE/#@name\", @volume, @pitch)\n"
      "      end\n"
      "    end\n"
      "    def self.stop\n"
      "      Audio.se_stop\n"
      "    end\n"
      "    def initialize(name = \"\", volume = 100, pitch = 100)\n"
      "      super(name, volume, pitch)\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 1
      "  module Cache\n"
      "    @cache = {}\n"
      "    def self.load_bitmap(dir, name, hue=0)\n"
      "      path = dir + name\n"
      "      key = hue == 0 ? path : [path, hue]\n"
      "      if !@cache[key] || @cache[key].disposed?\n"
      "        if name == \"\"\n"
      "          @cache[key] = Bitmap.new(32, 32)\n"
      "        else\n"
      "          @cache[key] = Bitmap.new(key)\n"
      "          @cache[key].hue_change(hue)\n"
      "        end\n"
      "      end\n"
      "      @cache[key]\n"
      "    end\n"
      "    def self.animation(name, hue)\n"
      "      load_bitmap(\"Graphics/Animations/\", name, hue)\n"
      "    end\n"
      "    def self.autotile(name)\n"
      "      load_bitmap(\"Graphics/Autotiles/\", name)\n"
      "    end\n"
      "    def self.battleback(name)\n"
      "      load_bitmap(\"Graphics/Battlebacks/\", name)\n"
      "    end\n"
      "    def self.battler(name, hue)\n"
      "      load_bitmap(\"Graphics/Battlers/\", name, hue)\n"
      "    end\n"
      "    def self.character(name, hue)\n"
      "      load_bitmap(\"Graphics/Characters/\", name, hue)\n"
      "    end\n"
      "    def self.fog(name, hue)\n"
      "      load_bitmap(\"Graphics/Fogs/\", name, hue)\n"
      "    end\n"
      "    def self.gameover(name)\n"
      "      load_bitmap(\"Graphics/Gameovers/\", name)\n"
      "    end\n"
      "    def self.icon(name)\n"
      "      load_bitmap(\"Graphics/Icons/\", name)\n"
      "    end\n"
      "    def self.panorama(name, hue)\n"
      "      load_bitmap(\"Graphics/Panoramas/\", name, hue)\n"
      "    end\n"
      "    def self.picture(name)\n"
      "      load_bitmap(\"Graphics/Pictures/\", name)\n"
      "    end\n"
      "    def self.tileset(name)\n"
      "      load_bitmap(\"Graphics/Tilesets/\", name)\n"
      "    end\n"
      "    def self.title(name)\n"
      "      load_bitmap(\"Graphics/Titles/\", name)\n"
      "    end\n"
      "    def self.transition(name)\n"
      "      load_bitmap(\"Graphics/Transitions/\", name)\n"
      "    end\n"
      "    def self.windowskin(name)\n"
      "      load_bitmap(\"Graphics/Windowskins/\", name)\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 1
      "  class Sprite < ::Sprite\n"
      "    @@_animations = []\n"
      "    @@_reference_count = {}\n"
      "    def whiten\n"
      "      self.opacity = 255\n"
      "      self.blend_type = 0\n"
      "      self.color = Color.new(255.0, 255.0, 255.0, 128.0)\n"
      "      @_appear_duration = 0\n"
      "      @_collapse_duration = 0\n"
      "      @_escape_duration = 0\n"
      "      @_whiten_duration = 16\n"
      "    end\n"
      "    def appear\n"
      "      self.opacity = 0\n"
      "      self.blend_type = 0\n"
      "      self.color = Color.new(0.0, 0.0, 0.0, 0.0)\n"
      "      @_appear_duration = 16\n"
      "      @_collapse_duration = 0\n"
      "      @_escape_duration = 0\n"
      "      @_whiten_duration = 0\n"
      "    end\n"
      "    def escape\n"
      "      self.opacity = 255\n"
      "      self.blend_type = 0\n"
      "      self.color = Color.new(0.0, 0.0, 0.0, 0.0)\n"
      "      @_appear_duration = 0\n"
      "      @_collapse_duration = 0\n"
      "      @_escape_duration = 32\n"
      "      @_whiten_duration = 0\n"
      "    end\n"
      "    def collapse\n"
      "      self.opacity = 255\n"
      "      self.blend_type = 1\n"
      "      self.color = Color.new(255.0, 64.0, 64.0, 255.0)\n"
      "      @_appear_duration = 0\n"
      "      @_collapse_duration = 48\n"
      "      @_escape_duration = 0\n"
      "      @_whiten_duration = 0\n"
      "    end\n"
      "    def damage(value, critical)\n"
      "      warn_unimplemented(\"RPG::Sprite#damage\")\n"
      "    end\n"
      "    def animation(animation, hit)\n"
      "      warn_unimplemented(\"RPG::Sprite#animation\")\n"
      "    end\n"
      "    def loop_animation(animation)\n"
      "      warn_unimplemented(\"RPG::Sprite#loop_animation\")\n"
      "    end\n"
      "    def blink_on\n"
      "      @_blink = true\n"
      "    end\n"
      "    def blink_off\n"
      "      @_blink = false\n"
      "      self.color = Color.new(0.0, 0.0, 0.0, 0.0)\n"
      "    end\n"
      "    def blink?\n"
      "      @_blink\n"
      "    end\n"
      "    def effect?\n"
      "      @_animation_duration > 0 || @_appear_duration > 0 || @_collapse_duration > 0 || @_damage_duration > 0 || @_escape_duration > 0 || @_whiten_duration > 0\n"
      "    end\n"
      "    def update\n"
      "      warn_unimplemented(\"RPG::Sprite#update\")\n"
      "    end\n"
      "    def initialize(viewport = nil)\n"
      "      super(viewport)\n"
      "      @_animation_duration = 0\n"
      "      @_appear_duration = 0\n"
      "      @_blink = false\n"
      "      @_collapse_duration = 0\n"
      "      @_damage_duration = 0\n"
      "      @_escape_duration = 0\n"
      "      @_whiten_duration = 0\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 1
      "  class Weather\n"
      "    attr_accessor :max, :ox, :oy, :type\n"
      "    def initialize(viewport=nil)\n"
      "      warn_unimplemented(\"RPG::Weather.new\")\n"
      "    end\n"
      "    def update\n"
      "      warn_unimplemented(\"RPG::Weather#update\")\n"
      "    end\n"
      "    def dispose\n"
      "      warn_unimplemented(\"RPG::Weather#dispose\")\n"
      "    end\n"
      "  end\n"
#endif
      "end\n"
      "\n"
      // TODO: implement fake DL and Win32API
#if RGSS == 3
      "module DL\n"
      "end\n"
#elif RGSS == 1
      "class Hangup < Exception\n"
      "end\n"
#endif
      "\n"
#if RGSS == 3
      "def rgss_stop\n"
      "  loop { Graphics.update }\n"
      "end\n"
      "def msgbox(*args)\n"
      "  print *args\n"
      "end\n"
      "def msgbox_p(*args)\n"
      "  p *args\n"
      "end\n"
      "RGSS_VERSION = \"3.0.1\"\n"
#endif
      "def save_data(obj, filename)\n"
      "  File.open(filename.gsub(/\\\\/, \"/\"), \"wb\") do|f|\n"
      "    Marshal.dump(obj, f)\n"
      "  end\n"
      "end\n"
  );
}

static void load_scripts() {
  bool retry = true;
  while(retry) {
    retry = false;
    rb_rescue2(
        load_scripts2, Qnil,
        rescue_reset, (VALUE)&retry,
        rb_eRGSSReset, NULL);
  }
}

static VALUE rescue_reset(VALUE data, VALUE e) {
  (void) e;
  disposeAll();
  rb_gc_start();
  *(bool*)data = true;
  return Qnil;
}

static VALUE load_scripts2(VALUE data) {
  (void) data;
  rb_eval_string(
      /* TODO: determine script path from Game.ini */
      "scripts_fname = "SCRIPT_PATH"\n"
      "$RGSS_SCRIPTS = load_data(scripts_fname)\n"
      "$RGSS_SCRIPTS.each do|section|\n"
      "  section.insert(3, Zlib::Inflate::inflate(section[2]))\n"
      "end\n"
      "$RGSS_SCRIPTS.each_with_index do|section, idx|\n"
      "  script = section[3].dup\n"
#if RGSS == 3
      "  script.force_encoding(\"utf-8\")\n"
#endif
#if RGSS == 3
      "  filename = sprintf(\"{%04d}\", idx)\n"
#else
      "  filename = sprintf(\"Section%03d\", idx)\n"
#endif
      "  eval(script, TOPLEVEL_BINDING, filename)\n"
      "end\n"
  );
  return Qnil;
}

#if RGSS == 3
static VALUE rb_rgss_main(VALUE self) {
  (void) self;
  bool retry = true;
  while(retry) {
    retry = false;
    rb_rescue2(
        rb_rgss_main2, Qnil,
        rescue_reset, (VALUE)&retry,
        rb_eRGSSReset, NULL);
  }
  return Qnil;
}
static VALUE rb_rgss_main2(VALUE data) {
  (void) data;
  return rb_yield(Qnil);
}
#endif
