#include <ruby.h>
#include "main_rb.h"
#include "RGSSReset.h"

#if RGSS == 3
#define TERMS "Terms"
#define SCRIPT_PATH "\"Data/Scripts.rvdata2\""
#elif RGSS == 2
#define TERMS "Terms"
#define SCRIPT_PATH "\"Data/Scripts.rvdata\""
#else
#define TERMS "Words"
#define SCRIPT_PATH "\"Data/Scripts.rxdata\""
#endif

static VALUE rescue_any(VALUE data, VALUE e);
static VALUE main_rb2(VALUE data);
static void load_libs(void);
static void load_scripts(void);
static VALUE rescue_reset(VALUE data, VALUE e);
static VALUE load_scripts2(VALUE data);

VALUE main_rb(VALUE data) {
  return rb_rescue2(main_rb2, data, rescue_any, Qnil, rb_eException, NULL);
}

static VALUE rescue_any(VALUE data, VALUE e) {
  (void) data;
  (void) e;
  rb_eval_string(
      "  $stderr.print(\"#{$!.class}: #{$!.message}\\n\")\n"
      "  $!.backtrace.each do|frame|\n"
      "    $stderr.print(\"\\tfrom #{frame}\\n\")\n"
      "  end\n"
  );
  return Qnil;
}

static VALUE main_rb2(VALUE data) {
  (void) data;
  load_libs();
  load_scripts();
  return Qnil;
}

static void load_libs() {
  rb_eval_string(
#if RGSS < 3
      "$KCODE = \"u\"\n"
#endif
      /* TODO: this is only for developing purpose. */
      /* We want to remove it when it becomes unnecessary. */
      "def warn_unimplemented(name)\n"
      "  unimplemented_warnings = eval(\"$unimplemented_warnings ||= {}\")\n"
      "  if !unimplemented_warnings[name]\n"
      "    unimplemented_warnings[name] = true\n"
      "    $stderr.puts \"unimplemented: #{name}\"\n"
      "  end\n"
      "end\n"
      "class Module\n"
      "  def attr_unimplemented(*names)\n"
      "    names.each do|name|\n"
      "      class_eval(\n"
      "        \"def #{name}\\n\" +\n"
      "        \"  warn_unimplemented(\\\"#{self}\\##{name}\\\")\\n\" +\n"
      "        \"  @#{name}\\n\" +\n"
      "        \"end\\n\" +\n"
      "        \"def #{name}=(#{name})\\n\" +\n"
      "        \"  warn_unimplemented(\\\"#{self}\\##{name}\\\")\\n\" +\n"
      "        \"  @#{name} = #{name}\\n\" +\n"
      "        \"end\\n\"\n"
      "      )\n"
      "    end\n"
      "  end\n"
      "end\n"
      "module Audio\n"
#if RGSS == 3
      "  def self.setup_midi\n"
      "    warn_unimplemented(\"Audio.setup_midi\")\n"
      "  end\n"
#endif
#if RGSS == 3
      "  def self.bgm_play(path, volume=nil, pitch=nil, pos=nil)\n"
      "    warn_unimplemented(\"Audio.bgm_play\")\n"
      "  end\n"
#else
      "  def self.bgm_play(path, volume=nil, pitch=nil)\n"
      "    warn_unimplemented(\"Audio.bgm_play\")\n"
      "  end\n"
#endif
      "  def self.bgm_stop\n"
      "    warn_unimplemented(\"Audio.bgm_stop\")\n"
      "  end\n"
      "  def self.bgm_fade(time)\n"
      "    warn_unimplemented(\"Audio.bgm_fade\")\n"
      "  end\n"
#if RGSS == 3
      "  def self.bgm_pos\n"
      "    warn_unimplemented(\"Audio.bgm_pos\")\n"
      "    0\n"
      "  end\n"
#endif
#if RGSS == 3
      "  def self.bgs_play(path, volume=nil, pitch=nil, pos=nil)\n"
      "    warn_unimplemented(\"Audio.bgs_play\")\n"
      "  end\n"
#else
      "  def self.bgs_play(path, volume=nil, pitch=nil)\n"
      "    warn_unimplemented(\"Audio.bgs_play\")\n"
      "  end\n"
#endif
      "  def self.bgs_stop\n"
      "    warn_unimplemented(\"Audio.bgs_stop\")\n"
      "  end\n"
      "  def self.bgs_fade(time)\n"
      "    warn_unimplemented(\"Audio.bgs_fade\")\n"
      "  end\n"
#if RGSS == 3
      "  def self.bgs_pos\n"
      "    warn_unimplemented(\"Audio.bgs_pos\")\n"
      "    0\n"
      "  end\n"
#endif
      "  def self.me_play(path, volume=nil, pitch=nil)\n"
      "    warn_unimplemented(\"Audio.me_play\")\n"
      "  end\n"
      "  def self.me_stop\n"
      "    warn_unimplemented(\"Audio.me_stop\")\n"
      "  end\n"
      "  def self.me_fade(time)\n"
      "    warn_unimplemented(\"Audio.me_fade\")\n"
      "  end\n"
      "  def self.se_play(path, volume=nil, pitch=nil)\n"
      "    warn_unimplemented(\"Audio.se_play\")\n"
      "  end\n"
      "  def self.se_stop\n"
      "    warn_unimplemented(\"Audio.se_stop\")\n"
      "  end\n"
      "end\n"
      "class Bitmap\n"
      "  def blur\n"
      "    warn_unimplemented(\"Bitmap#blur\")\n"
      "  end\n"
      "  def radial_blur\n"
      "    warn_unimplemented(\"Bitmap#radial_blur\")\n"
      "  end\n"
      "  def stretch_blt(*args)\n"
      "    warn_unimplemented(\"Bitmap#stretch_blt\")\n"
      "  end\n"
      "  def hue_change(hue)\n"
      "    warn_unimplemented(\"Bitmap#hue_change\")\n"
      "  end\n"
      "  def gradient_fill_rect(*args)\n"
      "    warn_unimplemented(\"Bitmap#gradient_fill_rect\")\n"
      "  end\n"
      "  def rect\n"
      "    Rect.new(0, 0, width, height)\n"
      "  end\n"
      "end\n"
      "class Font\n"
#if RGSS == 3
      "  @@default_name = \"VL Gothic\"\n"
      "  @@default_size = 24\n"
#elif RGSS == 2
      "  @@default_name = [\"UmePlus Gothic\", \"ＭＳ ゴシック\", \"Courier New\"] \n"
      "  @@default_size = 20\n"
#else
      "  @@default_name = \"ＭＳ Ｐゴシック\"\n"
      "  @@default_size = 22\n"
#endif
      "  @@default_bold = false\n"
      "  @@default_italic = false\n"
#if RGSS == 3
      "  @@default_outline = true\n"
      "  @@default_shadow = false\n"
#elif RGSS == 2
      "  @@default_shadow = true\n"
#endif
      "  @@default_color = Color.new(255, 255, 255, 255)\n"
#if RGSS == 3
      "  @@default_out_color = Color.new(0, 0, 0, 128)\n"
#endif
      "  def self.default_name\n"
      "    @@default_name\n"
      "  end\n"
      "  def self.default_name=(default_name)\n"
      "    @@default_name = default_name\n"
      "  end\n"
      "  def self.default_size\n"
      "    @@default_size\n"
      "  end\n"
      "  def self.default_size=(default_size)\n"
      "    @@default_size = default_size\n"
      "  end\n"
      "  def self.default_bold\n"
      "    @@default_bold\n"
      "  end\n"
      "  def self.default_bold=(default_bold)\n"
      "    @@default_bold = default_bold\n"
      "  end\n"
      "  def self.default_italic\n"
      "    @@default_italic\n"
      "  end\n"
      "  def self.default_italic=(default_italic)\n"
      "    @@default_italic = default_italic\n"
      "  end\n"
#if RGSS == 3
      "  def self.default_outline\n"
      "    @@default_outline\n"
      "  end\n"
      "  def self.default_outline=(default_outline)\n"
      "    @@default_outline = default_outline\n"
      "  end\n"
#endif
#if RGSS >= 2
      "  def self.default_shadow\n"
      "    @@default_shadow\n"
      "  end\n"
      "  def self.default_shadow=(default_shadow)\n"
      "    @@default_shadow = default_shadow\n"
      "  end\n"
#endif
      "  def self.default_color\n"
      "    @@default_color\n"
      "  end\n"
      "  def self.default_color=(default_color)\n"
      "    @@default_color = default_color\n"
      "  end\n"
#if RGSS == 3
      "  def self.default_out_color\n"
      "    @@default_out_color\n"
      "  end\n"
      "  def self.default_out_color=(default_out_color)\n"
      "    @@default_out_color = default_out_color\n"
      "  end\n"
#endif
      "end\n"
      "module Graphics\n"
      "end\n"
      "class Plane\n"
      "  attr_unimplemented :bitmap, :blend_type, :opacity, :ox, :oy, :tone, :visible, :z, :zoom_x, :zoom_y\n"
      "  def dispose\n"
      "    warn_unimplemented(\"Plane#dispose\")\n"
      "  end\n"
      "  def disposed?\n"
      "    warn_unimplemented(\"Plane#disposed?\")\n"
      "    false\n"
      "  end\n"
      "  def initialize(viewport=nil)\n"
      "    warn_unimplemented(\"Plane.new\")\n"
      "    @bitmap = Bitmap.new(1,1)\n"
      "    @viewport = viewport\n"
      "    @visible = true\n"
      "    @z = 0\n"
      "    @ox = 0\n"
      "    @oy = 0\n"
      "    @zoom_x = 1.0\n"
      "    @zoom_y = 1.0\n"
      "    @opacity = 255\n"
      "    @blend_type = 0\n"
      "    @color = Color.new(0, 0, 0, 0)\n"
      "    @tone = Tone.new(0, 0, 0, 0)\n"
      "  end\n"
      "end\n"
      "class Sprite\n"
      "  def flash(color, condition)\n"
      "    warn_unimplemented(\"Sprite#flash\")\n"
      "  end\n"
      "  def update\n"
      "    warn_unimplemented(\"Sprite#update\")\n"
      "  end\n"
      "end\n"
      "class Viewport\n"
      "  def flash(color, duration)\n"
      "    warn_unimplemented(\"Viewport#flash\")\n"
      "  end\n"
      "  def update\n"
      "    warn_unimplemented(\"Viewport#update\")\n"
      "  end\n"
      "end\n"
      "class Window\n"
      "  attr_unimplemented :active, :arrows_visible, :back_opacity, :contents_opacity, :cursor_rect, :opacity, :pause, :stretch, :tone, :viewport\n"
      "  def opacity=(opacity)\n"
      "    warn_unimplemented(\"Window#opacity\")\n"
      "    @opacity = [[opacity, 0].max, 255].min\n"
      "  end\n"
      "  def contents_opacity=(contents_opacity)\n"
      "    warn_unimplemented(\"Window#contents_opacity\")\n"
      "    @contents_opacity = [[contents_opacity, 0].max, 255].min\n"
      "  end\n"
      "  def update\n"
      "    warn_unimplemented(\"Window#update\")\n"
      "  end\n"
      "  alias_method :initialize_super, :initialize\n"
      "  def initialize(*args)\n"
      "    initialize_super(*args)\n"
      "    @cursor_rect = Rect.new(0, 0, 0, 0)\n"
      "    @ox = 0\n"
      "    @oy = 0\n"
      "    @tone = Tone.new(0.0, 0.0, 0.0, 0.0)\n"
      "    @active = true\n"
      "    @arrows_visible = true\n"
      "    @pause = false\n"
      "    @viewport = nil\n"
      "    @padding = 12\n"
      "    @padding_bottom = 12\n"
      "    @opacity = 255\n"
      "    @back_opacity = 192\n"
      "    @contents_opacity = 255\n"
      "    @tone = Tone.new(0, 0, 0, 0)\n"
      "    @stretch = true\n"
      "  end\n"
      "end\n"
      "\n"
      "module RPG\n"
      "  class Map\n"
      "    attr_accessor :autoplay_bgm, :autoplay_bgs, :bgm, :bgs, :data, :encounter_list, :encounter_step, :events, :height, :width\n"
#if RGSS >= 2
      "    attr_accessor :disable_dashing, :parallax_loop_x, :parallax_loop_y, :parallax_name, :parallax_show, :parallax_sx, :parallax_sy, :scroll_type\n"
#endif
#if RGSS == 3
      "    attr_accessor :battleback1_name, :battleback2_name, :display_name, :note, :specify_battleback, :tileset_id\n"
#endif
#if RGSS == 1
      "    attr_accessor :tileset_id\n"
#endif
      "    def initialize(width, height)\n"
#if RGSS == 3
      "      @autoplay_bgm = false\n"
      "      @autoplay_bgs = false\n"
      "      @battleback1_name = \"\"\n"
      "      @battleback2_name = \"\"\n"
      "      @bgm = RPG::BGM.new\n"
      "      @bgs = RPG::BGS.new(\"\", 80)\n"
      "      @data = Table.new(width, height, 4)\n"
      "      @disable_dashing = false\n"
      "      @display_name = \"\"\n"
      "      @encounter_list = []\n"
      "      @encounter_step = 30\n"
      "      @events = {}\n"
      "      @height = height\n"
      "      @note = \"\"\n"
      "      @parallax_loop_x = false\n"
      "      @parallax_loop_y = false\n"
      "      @parallax_name = \"\"\n"
      "      @parallax_show = false\n"
      "      @parallax_sx = 0\n"
      "      @parallax_sy = 0\n"
      "      @scroll_type = 0\n"
      "      @specify_battleback = false\n"
      "      @tileset_id = 1\n"
      "      @width = width\n"
#elif RGSS == 2
      "      @autoplay_bgm = false\n"
      "      @autoplay_bgs = false\n"
      "      @bgm = RPG::BGM.new\n"
      "      @bgs = RPG::BGS.new(\"\", 80)\n"
      "      @data = Table.new(width, height, 3)\n"
      "      @disable_dashing = false\n"
      "      @encounter_list = []\n"
      "      @encounter_step = 30\n"
      "      @events = {}\n"
      "      @height = height\n"
      "      @parallax_loop_x = false\n"
      "      @parallax_loop_y = false\n"
      "      @parallax_name = \"\"\n"
      "      @parallax_show = false\n"
      "      @parallax_sx = 0\n"
      "      @parallax_sy = 0\n"
      "      @scroll_type = 0\n"
      "      @width = width\n"
#else
      "      @autoplay_bgm = false\n"
      "      @autoplay_bgs = false\n"
      "      @bgm = RPG::AudioFile.new\n"
      "      @bgs = RPG::AudioFile.new(\"\", 80)\n"
      "      @data = Table.new(width, height, 3)\n"
      "      @encounter_list = []\n"
      "      @encounter_step = 30\n"
      "      @events = {}\n"
      "      @height = height\n"
      "      @tileset_id = 1\n"
      "      @width = width\n"
#endif
      "    end\n"
#if RGSS == 3
      "    class Encounter\n"
      "      attr_accessor :region_set, :troop_id, :weight\n"
      "      def initialize\n"
      "        @region_set = []\n"
      "        @troop_id = 1\n"
      "        @weight = 10\n"
      "      end\n"
      "    end\n"
#endif
      "  end\n"
      "  class MapInfo\n"
      "    attr_accessor :expanded, :name, :order, :parent_id, :scroll_x, :scroll_y\n"
      "    def initialize\n"
      "      @expanded = false\n"
      "      @name = \"\"\n"
      "      @order = 0\n"
      "      @parent_id = 0\n"
      "      @scroll_x = 0\n"
      "      @scroll_y = 0\n"
      "    end\n"
      "  end\n"
#if RGSS == 2
      "  class Area\n"
      "    attr_accessor :encounter_list, :id, :map_id, :name, :order, :rect\n"
      "    def initialize\n"
      "      @encounter_list = []\n"
      "      @id = 0\n"
      "      @map_id = 0\n"
      "      @name = \"\"\n"
      "      @order = 0\n"
      "      @rect = Rect.new(0, 0, 0, 0)\n"
      "    end\n"
      "  end\n"
#endif
      "  class Event\n"
      "    attr_accessor :id, :name, :pages, :x, :y\n"
      "    def initialize(x, y)\n"
      "      @id = 0\n"
      "      @name = \"\"\n"
      "      @pages = [RPG::Event::Page.new]\n"
      "      @x = x\n"
      "      @y = y\n"
      "    end\n"
      "    class Page\n"
      "      attr_accessor :condition, :direction_fix, :graphic, :list, :move_frequency, :move_route, :move_speed, :move_type, :step_anime, :through, :trigger, :walk_anime\n"
#if RGSS >= 2
      "      attr_accessor :priority_type\n"
#elif RGSS == 1
      "      attr_accessor :always_on_top\n"
#endif
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Event::Page.new\")\n"
      "      end\n"
      "      class Condition\n"
      "        attr_accessor :self_switch_ch, :self_switch_valid, :switch1_id, :switch1_valid, :switch2_id, :switch2_valid, :variable_id, :variable_valid, :variable_value\n"
#if RGSS >= 2
      "        attr_accessor :actor_id, :actor_valid, :item_id, :item_valid\n"
#endif
      "        def initialize\n"
      "          warn_unimplemented(\"RPG::Event::Page::Condition.new\")\n"
      "        end\n"
      "      end\n"
      "      class Graphic\n"
      "        attr_accessor :character_name, :direction, :pattern, :tile_id\n"
#if RGSS >= 2
      "        attr_accessor :character_index\n"
#elif RGSS == 1
      "        attr_accessor :blend_type, :character_hue, :character_name, :opacity, :tile_id\n"
#endif
      "        def initialize\n"
      "          warn_unimplemented(\"RPG::Event::Page::Graphic.new\")\n"
      "        end\n"
      "      end\n"
      "    end\n"
      "  end\n"
      "  class EventCommand\n"
      "    attr_accessor :code, :indent, :parameters\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::EventCommand.new\")\n"
      "    end\n"
      "  end\n"
      "  class MoveRoute\n"
      "    attr_accessor :list, :repeat, :skippable\n"
#if RGSS >= 2
      "    attr_accessor :wait\n"
#endif
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::MoveRoute.new\")\n"
      "    end\n"
      "  end\n"
      "  class MoveCommand\n"
      "    attr_accessor :code, :parameters\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::MoveCommand.new\")\n"
      "    end\n"
      "  end\n"
#if RGSS >= 2
      "  class BaseItem\n"
      "    attr_accessor :description, :icon_index, :id, :name, :note\n"
#if RGSS == 3
      "    attr_accessor :features\n"
      "    class Feature\n"
      "      attr_accessor :code, :data_id, :value\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::BaseItem::Feature.new\")\n"
      "      end\n"
      "    end\n"
#endif
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::BaseItem.new\")\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Actor < BaseItem\n"
      "    attr_accessor :character_index, :character_name, :class_id, :equips, :face_index, :face_name, :initial_level, :max_level, :nickname\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Actor.new\")\n"
      "    end\n"
      "  end\n"
#else
      "  class Actor\n"
      "    attr_accessor :armor1_id, :armor2_id, :armor3_id, :armor4_id, :class_id, :exp_basis, :exp_inflation, :id, :initial_level, :name, :parameters, :weapon_id\n"
#if RGSS == 2
      "    attr_accessor :auto_battle, :character_index, :character_name, :critical_bonus, :face_index, :face_name, :fix_equipment, :pharmacology, :super_guard, :two_swords_style\n"
#else
      "    attr_accessor :armor1_fix, :armor2_fix, :armor3_fix, :armor4_fix, :battler_hue, :battler_name, :character_hue, :character_name, :final_level, :weapon_fix\n"
#endif
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Actor.new\")\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Class < BaseItem\n"
#else
      "  class Class\n"
#endif
      "    attr_accessor :learnings\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Class.new\")\n"
      "    end\n"
#if RGSS == 3
      "    attr_accessor :exp_params, :params\n"
      "    def exp_for_level(level)\n"
      "      level = level.to_f\n"
      "      a = @exp_params[0].to_f * (level - 1) ** (0.9 + @exp_params[2].to_f / 250) * level * (level + 1)\n"
      "      b = 6 + level ** 2 / 50 / @exp_params[3].to_f\n"
      "      (a / b + (level - 1) * @exp_params[1].to_f).round.to_i\n"
      "    end\n"
#else
      "    attr_accessor :armor_set, :element_ranks, :id, :name, :position, :state_ranks, :weapon_set\n"
#if RGSS == 2
      "    attr_accessor :skill_name, :skill_name_valid\n"
#endif
#endif
      "    class Learning\n"
      "      attr_accessor :level, :skill_id\n"
#if RGSS == 3
      "      attr_accessor :note\n"
#endif
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Class::Learning.new\")\n"
      "      end\n"
      "    end\n"
      "  end\n"
#if RGSS >= 2
      "  class UsableItem < BaseItem\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::UsableItem.new\")\n"
      "    end\n"
#if RGSS == 3
      "    attr_accessor :message1, :message2, :mp_cost, :required_wtype_id1, :required_wtype_id2, :stype_id, :tp_cost\n"
      "    def for_opponent?\n"
      "      [1, 2, 3, 4, 5, 6].include?(@scope)\n"
      "    end\n"
      "    def for_friend?\n"
      "      [7, 8, 9, 10, 11].include?(@scope)\n"
      "    end\n"
      "    def for_dead_friend?\n"
      "      [9, 10].include?(@scope)\n"
      "    end\n"
      "    def for_user?\n"
      "      @scope == 11\n"
      "    end\n"
      "    def for_one?\n"
      "      [1, 3, 7, 9, 11].include?(@scope)\n"
      "    end\n"
      "    def for_random?\n"
      "      [3, 4, 5, 6].include?(@scope)\n"
      "    end\n"
      "    def number_of_targets\n"
      "      [nil, nil, nil, 1, 2, 3, 4][@scope]\n"
      "    end\n"
      "    def for_all?\n"
      "      [2, 9, 10].include?(@scope)\n"
      "    end\n"
      "    def need_selection?\n"
      "      [1, 7, 9].include?(@scope)\n"
      "    end\n"
      "    def battle_ok?\n"
      "      [0, 1].include?(@occasion)\n"
      "    end\n"
      "    def menu_ok?\n"
      "      [0, 2].include?(@occasion)\n"
      "    end\n"
      "    def certain?\n"
      "      @hit_type == 0\n"
      "    end\n"
      "    def physical?\n"
      "      @hit_type == 1\n"
      "    end\n"
      "    def magical?\n"
      "      @hit_type == 2\n"
      "    end\n"
      "    class Damage\n"
      "      attr_accessor :critical, :element_id, :formula, :type, :variance\n"
      "      def none?\n"
      "        @type == 0\n"
      "      end\n"
      "      def to_hp?\n"
      "        [1, 3, 5].include?(@type)\n"
      "      end\n"
      "      def to_mp?\n"
      "        [2, 4, 6].include?(@type)\n"
      "      end\n"
      "      def recover?\n"
      "        [3, 4].include?(@type)\n"
      "      end\n"
      "      def drain?\n"
      "        [5, 6].include?(@type)\n"
      "      end\n"
      "      def sign\n"
      "        recover? ? -1 : 1\n"
      "      end\n"
      "      def eval(a, b, v)\n"
      "        [Kernel.eval(@formula), 0].max * self.sign rescue 0\n"
      "      end\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::UsableItem::Damage.new\")\n"
      "      end\n"
      "    end\n"
      "    class Effect\n"
      "      attr_accessor :code, :data_id, :value1, :value2\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::UsableItem::Effect.new\")\n"
      "      end\n"
      "    end\n"
#else
      "    attr_accessor :absorb_damage, :animation_id, :atk_f, :base_damage, :common_event_id, :damage_to_mp, :element_set, :ignore_defense, :minus_state_set, :occasion, :physical_attack, :plus_state_set, :scope, :speed, :spi_f, :variance\n"
      "    def for_opponent?\n"
      "      [1, 2, 3, 4, 5, 6].include?(@scope)\n"
      "    end\n"
      "    def for_friend?\n"
      "      [7, 8, 9, 10, 11].include?(@scope)\n"
      "    end\n"
      "    def for_dead_friend?\n"
      "      [9, 10].include?(@scope)\n"
      "    end\n"
      "    def for_user?\n"
      "      @scope == 11\n"
      "    end\n"
      "    def for_one?\n"
      "      [1, 3, 4, 7, 9, 11].include?(@scope)\n"
      "    end\n"
      "    def for_two?\n"
      "      @scope == 5\n"
      "    end\n"
      "    def for_three?\n"
      "      @scope == 6\n"
      "    end\n"
      "    def for_random?\n"
      "      [4, 5, 6].include?(@scope)\n"
      "    end\n"
      "    def for_all?\n"
      "      [2, 8, 10].include?(@scope)\n"
      "    end\n"
      "    def dual?\n"
      "      @scope == 3\n"
      "    end\n"
      "    def need_selection?\n"
      "      [1, 3, 7, 9].include?(@scope)\n"
      "    end\n"
      "    def battle_ok?\n"
      "      [0, 1].include?(@occasion)\n"
      "    end\n"
      "    def menu_ok?\n"
      "      [0, 2].include?(@occasion)\n"
      "    end\n"
#endif
      "  end\n"
#endif
#if RGSS == 3
      "  class Skill < UsableItem\n"
      "    attr_accessor :message1, :message2, :mp_cost, :required_wtype_id1, :required_wtype_id2, :stype_id, :tp_cost\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Skill.new\")\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class Skill < UsableItem\n"
      "    attr_accessor :hit, :message1, :message2, :mp_cost\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Skill.new\")\n"
      "    end\n"
      "  end\n"
#else
      "  class Skill\n"
      "    attr_accessor :agi_f, :animation1_id, :animation2_id, :atk_f, :common_event_id, :description, :dex_f, :element_set, :eva_f, :hit, :icon_name, :id, :int_f, :mdef_f, :menu_se, :minus_state_set, :name, :occasion, :pdef_f, :plus_state_set, :power, :scope, :sp_cost, :str_f, :variance\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Skill.new\")\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Item < UsableItem\n"
      "    attr_accessor :consumable, :itype_id, :price\n"
      "    def key_item?\n"
      "      @itype_id == 2\n"
      "    end\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Item.new\")\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class Item < UsableItem\n"
      "    attr_accessor :consumable, :hp_recovery, :hp_recovery_rate, :mp_recovery, :mp_recovery_rate, :parameter_points, :parameter_type, :price\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Item.new\")\n"
      "    end\n"
      "  end\n"
#else
      "  class Item\n"
      "    attr_accessor :animation1_id, :animation2_id, :common_event_id, :consumable, :description, :element_set, :hit, :icon_name, :id, :mdef_f, :menu_se, :minus_state_set, :name, :occasion, :parameter_points, :parameter_type, :pdef_f, :plus_state_set, :price, :recover_hp, :recover_hp_rate, :recover_sp, :recover_sp_rate, :scope, :variance\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Item.new\")\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class EquipItem < BaseItem\n"
      "    attr_accessor :etype_id, :params, :price\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::EquipItem.new\")\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Weapon < EquipItem\n"
      "    attr_accessor :animation_id, :wtype_id\n"
      "    def performance\n"
      "      @params[2] + @params[4] + @params.inject(&:+)\n"
      "    end\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Weapon.new\")\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class Weapon < BaseItem\n"
      "    attr_accessor :agi, :animation_id, :atk, :critical_bonus, :def, :dual_attack, :element_set, :fast_attack, :hit, :price, :spi, :state_set, :two_handed\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Weapon.new\")\n"
      "    end\n"
      "  end\n"
#else
      "  class Weapon\n"
      "    attr_accessor :agi_plus, :animation1_id, :animation2_id, :atk, :description, :dex_plus, :element_set, :icon_name, :id, :int_plus, :mdef, :minus_state_set, :name, :pdef, :plus_state_set, :price, :str_plus\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Weapon.new\")\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Armor < EquipItem\n"
      "    attr_accessor :atype_id\n"
      "    def performance\n"
      "      @params[3] + @params[5] + @params.inject(&:+)\n"
      "    end\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Armor.new\")\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class Armor < BaseItem\n"
      "    attr_accessor :agi, :atk, :auto_hp_recover, :def, :double_exp_gain, :element_set, :eva, :half_mp_cost, :kind, :prevent_critical, :price, :spi, :state_set\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Armor.new\")\n"
      "    end\n"
      "  end\n"
#else
      "  class Armor\n"
      "    attr_accessor :agi_plus, :auto_state_id, :description, :dex_plus, :eva, :guard_element_set, :guard_state_set, :icon_name, :id, :int_plus, :kind, :mdef, :name, :pdef, :price, :str_plus\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Armor.new\")\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class Enemy < BaseItem\n"
      "    attr_accessor :actions, :battler_hue, :battler_name, :drop_items, :exp, :gold, :params\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::Enemy.new\")\n"
      "    end\n"
      "    class Action\n"
      "      attr_accessor :condition_param1, :condition_param2, :condition_type, :rating, :skill_id\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Enemy::Action.new\")\n"
      "      end\n"
      "    end\n"
      "    class DropItem\n"
      "      attr_accessor :data_id, :denominator, :kind\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Enemy::DropItem.new\")\n"
      "      end\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class Enemy\n"
      "    attr_accessor :actions, :agi, :atk, :battler_hue, :battler_name, :def, :drop_item1, :drop_item2, :element_ranks, :eva, :exp, :gold, :has_critical, :hit, :id, :levitate, :maxhp, :maxmp, :name, :note, :spi, :state_ranks\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Enemy.new\")\n"
      "    end\n"
      "    class Action\n"
      "      attr_accessor :basic, :condition_param1, :condition_param2, :condition_type, :kind, :rating, :skill_id\n"
      "      def skill?\n"
      "        @kind == 1\n"
      "      end\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Enemy::Action.new\")\n"
      "      end\n"
      "    end\n"
      "    class DropItem\n"
      "      attr_accessor :armor_id, :denominator, :item_id, :kind, :weapon_id\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Enemy::DropItem.new\")\n"
      "      end\n"
      "    end\n"
      "  end\n"
#else
      "  class Enemy\n"
      "    attr_accessor :actions, :agi, :animation1_id, :animation2_id, :armor_id, :atk, :battler_hue, :battler_name, :dex, :element_ranks, :eva, :exp, :gold, :id, :int, :item_id, :maxhp, :maxsp, :mdef, :name, :pdef, :state_ranks, :str, :treasure_prob, :weapon_id\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Enemy.new\")\n"
      "    end\n"
      "    class Action\n"
      "      attr_accessor :basic, :condition_hp, :condition_level, :condition_switch_id, :condition_turn_a, :condition_turn_b, :kind, :rating, :skill_id\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Enemy::Action.new\")\n"
      "      end\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 3
      "  class State < BaseItem\n"
      "    attr_accessor :auto_removal_timing, :chance_by_damage, :max_turns, :message1, :message2, :message3, :message4, :min_turns, :priority, :remove_at_battle_end, :remove_by_damage, :remove_by_restriction, :remove_by_walking, :restriction, :steps_to_remove\n"
      "    def initialize\n"
      "      super\n"
      "      warn_unimplemented(\"RPG::State.new\")\n"
      "    end\n"
      "  end\n"
#elif RGSS == 2
      "  class State\n"
      "    attr_accessor :id, :name, :icon_index, :restriction, :priority, :atk_rate, :def_rate, :spi_rate, :agi_rate, :nonresistance, :offset_by_opposite, :slip_damage, :reduce_hit_ratio, :battle_only, :release_by_damage, :hold_turn, :auto_release_prob, :message1, :message2, :message3, :message4, :element_set, :state_set, :note\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::State.new\")\n"
      "    end\n"
      "  end\n"
#elif RGSS == 1
      "  class State\n"
      "    attr_accessor :agi_rate, :animation_id, :atk_rate, :auto_release_prob, :battle_only, :cant_evade, :cant_get_exp, :dex_rate, :eva, :guard_element_set, :hit_rate, :hold_turn, :id, :int_rate, :maxhp_rate, :maxsp_rate, :mdef_rate, :minus_state_set, :name, :nonresistance, :pdef_rate, :plus_state_set, :rating, :restriction, :shock_release_prob, :slip_damage, :str_rate, :zero_hp\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::State.new\")\n"
      "    end\n"
      "  end\n"
#endif
      "  class Troop\n"
      "    attr_accessor :id, :name, :members, :pages\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Troop.new\")\n"
      "    end\n"
      "    class Member\n"
      "      attr_accessor :enemy_id, :hidden, :x, :y\n"
#if RGSS <= 2
      "      attr_accessor :immortal\n"
#endif
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Troop::Member.new\")\n"
      "      end\n"
      "    end\n"
      "    class Page\n"
      "      attr_accessor :condition, :list, :span\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Troop::Page.new\")\n"
      "      end\n"
      "      class Condition\n"
#if RGSS >= 2
      "        attr_accessor :turn_ending\n"
#endif
      "        attr_accessor :actor_hp, :actor_id, :actor_valid, :enemy_hp, :enemy_index, :enemy_valid, :switch_id, :switch_valid, :turn_a, :turn_b, :turn_valid\n"
      "        def initialize\n"
      "          warn_unimplemented(\"RPG::Troop::Page::Condition.new\")\n"
      "        end\n"
      "      end\n"
      "    end\n"
      "  end\n"
      "  class Animation\n"
      "    attr_accessor :frame_max, :frames, :id, :name, :position, :timings\n"
#if RGSS >= 2
      "    attr_accessor :animation1_hue, :animation1_name, :animation2_hue, :animation2_name\n"
#else
      "    attr_accessor :animation_hue, :animation_name\n"
#endif
#if RGSS == 3
      "    def to_screen?\n"
      "      @position == 3\n"
      "    end\n"
#endif
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Animation.new\")\n"
      "    end\n"
      "    class Frame\n"
      "      attr_accessor :cell_data, :cell_max\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Animation::Frame.new\")\n"
      "      end\n"
      "    end\n"
      "    class Timing\n"
      "      attr_accessor :flash_color, :flash_duration, :flash_scope, :frame, :se\n"
#if RGSS == 1
      "      attr_accessor :condition\n"
#endif
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::Animation::Timing.new\")\n"
      "      end\n"
      "    end\n"
      "  end\n"
#if RGSS == 3
      "  class Tileset\n"
      "    attr_accessor :flags, :id, :mode, :name, :note, :tileset_names\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Tileset.new\")\n"
      "    end\n"
      "  end\n"
#elif RGSS == 1
      "  class Tileset\n"
      "    attr_accessor :autotile_names, :battleback_name, :fog_blend_type, :fog_hue, :fog_name, :fog_opacity, :fog_sx, :fog_sy, :fog_zoom, :id, :name, :panorama_hue, :panorama_name, :passages, :priorities, :terrain_tags, :tileset_name\n"
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::Tileset.new\")\n"
      "    end\n"
      "  end\n"
#endif
      "  class CommonEvent\n"
      "    attr_accessor :id, :name, :trigger, :switch_id, :list\n"
#if RGSS == 3
      "    def autorun?\n"
      "      @trigger == 1\n"
      "    end\n"
      "    def parallel?\n"
      "      @trigger == 2\n"
      "    end\n"
#endif
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::CommonEvent.new\")\n"
      "    end\n"
      "  end\n"
      "  class System\n"
#if RGSS >= 2
      "    attr_accessor :airship, :boat, :game_title, :ship, :sounds, :terms, :version_id\n"
#endif
      "    attr_accessor :battle_bgm, :battle_end_me, :battler_hue, :battler_name, :edit_map_id, :elements, :gameover_me, :party_members, :start_map_id, :start_x, :start_y, :switches, :test_battlers, :test_troop_id, :title_bgm, :variables\n"
#if RGSS == 3
      "    attr_accessor :armor_types, :battleback1_name, :battleback2_name, :currency_unit, :japanese, :opt_display_tp, :opt_draw_title, :opt_extra_exp, :opt_floor_death, :opt_followers, :opt_slip_death, :opt_transparent, :opt_use_midi, :skill_types, :title1_name, :title2_name, :weapon_types, :window_tone\n"
#elif RGSS == 2
      "    attr_accessor :passages\n"
#else
      "    attr_accessor :actor_collapse_se, :battle_start_se, :battle_transition, :battleback_name, :buzzer_se, :cancel_se, :cursor_se, :decision_se, :enemy_collapse_se, :equip_se, :escape_se, :gameover_name, :load_se, :magic_number, :save_se, :shop_se, :title_name, :windowskin_name, :words\n"
#endif
      "    def initialize\n"
      "      warn_unimplemented(\"RPG::System.new\")\n"
      "    end\n"
      "    class "TERMS"\n"
#if RGSS == 3
      "      attr_accessor :basic, :commands, :etypes, :params\n"
#else
      "      attr_accessor :agi, :armor1, :armor2, :armor3, :armor4, :atk, :attack, :equip, :gold, :guard, :hp, :item, :skill, :weapon\n"
#if RGSS == 2
      "      attr_accessor :cancel, :continue, :def, :escape, :fight, :game_end, :hp_a, :level, :level_a, :mp, :mp_a, :new_game, :save, :shutdown, :spi, :status, :to_title, :weapon1, :weapon2\n"
#else
      "      attr_accessor :dex, :int, :mdef, :pdef, :sp, :str\n"
#endif
#endif
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::System::"TERMS".new\")\n"
      "      end\n"
      "    end\n"
      "    class TestBattler\n"
      "      attr_accessor :actor_id, :level\n"
#if RGSS == 3
      "      attr_accessor :equips\n"
#else
      "      attr_accessor :armor1_id, :armor2_id, :armor3_id, :armor4_id, :weapon_id\n"
#endif
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::System::TestBattler.new\")\n"
      "      end\n"
      "    end\n"
#if RGSS >= 2
      "    class Vehicle\n"
      "      attr_accessor :bgm, :character_index, :character_name, :start_map_id, :start_x, :start_y\n"
      "      def initialize\n"
      "        warn_unimplemented(\"RPG::System::Vehicle.new\")\n"
      "      end\n"
      "    end\n"
#endif
      "  end\n"
      "  class AudioFile\n"
      "    attr_accessor :name, :pitch, :volume\n"
      "    def initialize(name = \"\", volume = 100, pitch = 100)\n"
      "      @name = name\n"
      "      @pitch = pitch\n"
      "      @volume = volume\n"
      "    end\n"
      "  end\n"
#if RGSS >= 2
      "  class BGM < AudioFile\n"
#if RGSS == 3
      "    attr_accessor :pos\n"
      "    def replay\n"
      "      warn_unimplemented(\"RPG::BGM#replay\")\n"
      "    end\n"
      "    def play(pos=0)\n"
      "      if @name == \"\"\n"
      "        Audio.bgm_stop\n"
      "        @@last = BGM.new\n"
      "      else\n"
      "        Audio.bgm_play(\"Audio/BGM/#@name\", @volume, @pitch, pos)\n"
      "        @@last = self.clone\n"
      "      end\n"
      "    end\n"
#else
      "    def play\n"
      "      if @name == \"\"\n"
      "        Audio.bgm_stop\n"
      "        @@last = BGM.new\n"
      "      else\n"
      "        Audio.bgm_play(\"Audio/BGM/#@name\", @volume, @pitch)\n"
      "        @@last = self\n"
      "      end\n"
      "    end\n"
#endif
      "    def self.last\n"
#if RGSS == 3
      "      @@last.pos = Audio.bgm_pos\n"
#endif
      "      @@last\n"
      "    end\n"
      "    def self.stop\n"
      "      Audio.bgm_stop\n"
      "      @@last = BGM.new\n"
      "    end\n"
      "    def self.fade(time)\n"
      "      Audio.bgm_fade(time)\n"
      "      @@last = BGM.new\n"
      "    end\n"
      "    def initialize(name = \"\", volume = 100, pitch = 100)\n"
      "      super(name, volume, pitch)\n"
      "    end\n"
      "    @@last = BGM.new\n"
      "  end\n"
      "  class BGS < AudioFile\n"
#if RGSS == 3
      "    attr_accessor :pos\n"
      "    def replay\n"
      "      warn_unimplemented(\"RPG::BGS#replay\")\n"
      "    end\n"
      "    def play(pos=0)\n"
      "      if @name == \"\"\n"
      "        Audio.bgs_stop\n"
      "        @@last = BGS.new\n"
      "      else\n"
      "        Audio.bgs_play(\"Audio/BGS/#@name\", @volume, @pitch, pos)\n"
      "        @@last = self.clone\n"
      "      end\n"
      "    end\n"
#else
      "    def play\n"
      "      if @name == \"\"\n"
      "        Audio.bgs_stop\n"
      "        @@last = BGS.new\n"
      "      else\n"
      "        Audio.bgs_play(\"Audio/BGS/#@name\", @volume, @pitch)\n"
      "        @@last = self\n"
      "      end\n"
      "    end\n"
#endif
      "    def self.last\n"
#if RGSS == 3
      "      @@last.pos = Audio.bgs_pos\n"
#endif
      "      @@last\n"
      "    end\n"
      "    def self.stop\n"
      "      Audio.bgs_stop\n"
      "      @@last = BGS.new\n"
      "    end\n"
      "    def self.fade(time)\n"
      "      Audio.bgs_fade(time)\n"
      "      @@last = BGS.new\n"
      "    end\n"
      "    def initialize(name = \"\", volume = 100, pitch = 100)\n"
      "      super(name, volume, pitch)\n"
      "    end\n"
      "    @@last = BGS.new\n"
      "  end\n"
      "  class ME < AudioFile\n"
      "    def play\n"
      "      if @name == \"\"\n"
      "        Audio.me_stop\n"
      "      else\n"
      "        Audio.me_play(\"Audio/ME/#@name\", @volume, @pitch)\n"
      "      end\n"
      "    end\n"
      "    def self.stop\n"
      "      Audio.me_stop\n"
      "    end\n"
      "    def self.fade(time)\n"
      "      Audio.me_fade(time)\n"
      "    end\n"
      "    def initialize(name = \"\", volume = 100, pitch = 100)\n"
      "      super(name, volume, pitch)\n"
      "    end\n"
      "  end\n"
      "  class SE < AudioFile\n"
      "    def play\n"
      "      if @name != \"\"\n"
      "        Audio.se_play(\"Audio/SE/#@name\", @volume, @pitch)\n"
      "      end\n"
      "    end\n"
      "    def self.stop\n"
      "      Audio.se_stop\n"
      "    end\n"
      "    def initialize(name = \"\", volume = 100, pitch = 100)\n"
      "      super(name, volume, pitch)\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 1
      "  module Cache\n"
      "    @cache = {}\n"
      "    def self.load_bitmap(dir, name, hue=0)\n"
      "      path = dir + name\n"
      "      key = hue == 0 ? path : [path, hue]\n"
      "      if !@cache[key] || @cache[key].disposed?\n"
      "        if name == \"\"\n"
      "          @cache[key] = Bitmap.new(32, 32)\n"
      "        else\n"
      "          @cache[key] = Bitmap.new(key)\n"
      "          @cache[key].hue_change(hue)\n"
      "        end\n"
      "      end\n"
      "      @cache[key]\n"
      "    end\n"
      "    def self.animation(name, hue)\n"
      "      load_bitmap(\"Graphics/Animations/\", name, hue)\n"
      "    end\n"
      "    def self.autotile(name)\n"
      "      load_bitmap(\"Graphics/Autotiles/\", name)\n"
      "    end\n"
      "    def self.battleback(name)\n"
      "      load_bitmap(\"Graphics/Battlebacks/\", name)\n"
      "    end\n"
      "    def self.battler(name, hue)\n"
      "      load_bitmap(\"Graphics/Battlers/\", name, hue)\n"
      "    end\n"
      "    def self.character(name, hue)\n"
      "      load_bitmap(\"Graphics/Characters/\", name, hue)\n"
      "    end\n"
      "    def self.fog(name, hue)\n"
      "      load_bitmap(\"Graphics/Fogs/\", name, hue)\n"
      "    end\n"
      "    def self.gameover(name)\n"
      "      load_bitmap(\"Graphics/Gameovers/\", name)\n"
      "    end\n"
      "    def self.icon(name)\n"
      "      load_bitmap(\"Graphics/Icons/\", name)\n"
      "    end\n"
      "    def self.panorama(name, hue)\n"
      "      load_bitmap(\"Graphics/Panoramas/\", name, hue)\n"
      "    end\n"
      "    def self.picture(name)\n"
      "      load_bitmap(\"Graphics/Pictures/\", name)\n"
      "    end\n"
      "    def self.tileset(name)\n"
      "      load_bitmap(\"Graphics/Tilesets/\", name)\n"
      "    end\n"
      "    def self.title(name)\n"
      "      load_bitmap(\"Graphics/Titles/\", name)\n"
      "    end\n"
      "    def self.transition(name)\n"
      "      load_bitmap(\"Graphics/Transitions/\", name)\n"
      "    end\n"
      "    def self.windowskin(name)\n"
      "      load_bitmap(\"Graphics/Windowskins/\", name)\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 1
      "  class Sprite < ::Sprite\n"
      "    @@_animations = []\n"
      "    def whiten\n"
      "      warn_unimplemented(\"RPG::Sprite#whiten\")\n"
      "    end\n"
      "    def appear\n"
      "      warn_unimplemented(\"RPG::Sprite#appear\")\n"
      "    end\n"
      "    def escape\n"
      "      warn_unimplemented(\"RPG::Sprite#escape\")\n"
      "    end\n"
      "    def collapse\n"
      "      warn_unimplemented(\"RPG::Sprite#collapse\")\n"
      "    end\n"
      "    def damage(value, critical)\n"
      "      warn_unimplemented(\"RPG::Sprite#damage\")\n"
      "    end\n"
      "    def animation(animation, hit)\n"
      "      warn_unimplemented(\"RPG::Sprite#animation\")\n"
      "    end\n"
      "    def loop_animation(animation)\n"
      "      warn_unimplemented(\"RPG::Sprite#loop_animation\")\n"
      "    end\n"
      "    def blink_on\n"
      "      warn_unimplemented(\"RPG::Sprite#blink_on\")\n"
      "      @blink = true\n"
      "    end\n"
      "    def blink_off\n"
      "      warn_unimplemented(\"RPG::Sprite#blink_off\")\n"
      "      @blink = false\n"
      "    end\n"
      "    def blink?\n"
      "      warn_unimplemented(\"RPG::Sprite#blink?\")\n"
      "      @blink\n"
      "    end\n"
      "    def effect?\n"
      "      warn_unimplemented(\"RPG::Sprite#effect?\")\n"
      "      false\n"
      "    end\n"
      "    def update\n"
      "      warn_unimplemented(\"RPG::Sprite#update\")\n"
      "    end\n"
      "    def initialize(*args)\n"
      "      super(*args)\n"
      "      warn_unimplemented(\"RPG::Sprite.new\")\n"
      "    end\n"
      "  end\n"
#endif
#if RGSS == 1
      "  class Weather\n"
      "    attr_accessor :max, :ox, :oy, :type\n"
      "    def initialize(viewport=nil)\n"
      "      warn_unimplemented(\"RPG::Weather.new\")\n"
      "    end\n"
      "    def update\n"
      "      warn_unimplemented(\"RPG::Weather#update\")\n"
      "    end\n"
      "    def dispose\n"
      "      warn_unimplemented(\"RPG::Weather#dispose\")\n"
      "    end\n"
      "  end\n"
#endif
      "end\n"
      "\n"
      // TODO: implement fake DL and Win32API
#if RGSS == 3
      "module DL\n"
      "end\n"
#elif RGSS == 2
      "module NKF\n"
      "end\n"
#else
      "class Hangup\n"
      "end\n"
#endif
      "\n"
#if RGSS == 3
      "def rgss_main\n"
      "  yield\n"
      "rescue RGSSReset\n"
      "  GC.start\n"
      "  retry\n"
      "end\n"
      "def rgss_stop\n"
      "  loop { Graphics.update }\n"
      "end\n"
      "def msgbox(*args)\n"
      "  print *args\n"
      "end\n"
      "def msgbox_p(*args)\n"
      "  p *args\n"
      "end\n"
      "RGSS_VERSION = \"3.0.1\"\n"
#endif
      "def save_data(obj, filename)\n"
      "  File.open(filename.gsub(/\\\\/, \"/\"), \"wb\") do|f|\n"
      "    Marshal.dump(obj, f)\n"
      "  end\n"
      "end\n"
  );
}

static void load_scripts() {
  rb_rescue2(load_scripts2, Qnil, rescue_reset, Qnil, rb_eRGSSReset, NULL);
}

static VALUE rescue_reset(VALUE data, VALUE e) {
  (void) data;
  (void) e;
  rb_eval_string("retry");
  return Qnil;
}

static VALUE load_scripts2(VALUE data) {
  (void) data;
  rb_eval_string(
      /* TODO: determine script path from Game.ini */
      "$RGSS_SCRIPTS = load_data("SCRIPT_PATH")\n"
      "$RGSS_SCRIPTS.each do|num,title,script|\n"
      "  s = Zlib::Inflate::inflate(script)\n"
#if RGSS == 3
      "  s.force_encoding(\"utf-8\")\n"
#endif
      "  eval(s, binding, title)\n"
      "end\n"
  );
  return Qnil;
}
